// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AcceptInvitationApiV1CollaborationInvitationsAcceptPostData,
  AcceptInvitationApiV1CollaborationInvitationsAcceptPostErrors,
  AcceptInvitationApiV1CollaborationInvitationsAcceptPostResponses,
  AcceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPostData,
  AcceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPostErrors,
  AcceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPostResponses,
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostData,
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors,
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses,
  AnalyzeLocationImageApiV1LocationsAnalyzeImagePostData,
  AnalyzeLocationImageApiV1LocationsAnalyzeImagePostErrors,
  AnalyzeLocationImageApiV1LocationsAnalyzeImagePostResponses,
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostData,
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors,
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses,
  AutoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPostData,
  AutoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPostErrors,
  AutoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPostResponses,
  BatchUpdateItemsApiV1ItemsBatchPatchData,
  BatchUpdateItemsApiV1ItemsBatchPatchErrors,
  BatchUpdateItemsApiV1ItemsBatchPatchResponses,
  CalculateGridApiV1GridfinityCalculateGridGetData,
  CalculateGridApiV1GridfinityCalculateGridGetErrors,
  CalculateGridApiV1GridfinityCalculateGridGetResponses,
  CheckInItemApiV1ItemsItemIdCheckInPostData,
  CheckInItemApiV1ItemsItemIdCheckInPostErrors,
  CheckInItemApiV1ItemsItemIdCheckInPostResponses,
  CheckOutItemApiV1ItemsItemIdCheckOutPostData,
  CheckOutItemApiV1ItemsItemIdCheckOutPostErrors,
  CheckOutItemApiV1ItemsItemIdCheckOutPostResponses,
  ClassifyImageApiV1ImagesClassifyPostData,
  ClassifyImageApiV1ImagesClassifyPostErrors,
  ClassifyImageApiV1ImagesClassifyPostResponses,
  CreateApiKeyApiV1AdminApikeysPostData,
  CreateApiKeyApiV1AdminApikeysPostErrors,
  CreateApiKeyApiV1AdminApikeysPostResponses,
  CreateCategoryApiV1CategoriesPostData,
  CreateCategoryApiV1CategoriesPostErrors,
  CreateCategoryApiV1CategoriesPostResponses,
  CreateCategoryFromPathApiV1CategoriesFromPathPostData,
  CreateCategoryFromPathApiV1CategoriesFromPathPostErrors,
  CreateCategoryFromPathApiV1CategoriesFromPathPostResponses,
  CreateCheckoutApiV1BillingCheckoutPostData,
  CreateCheckoutApiV1BillingCheckoutPostErrors,
  CreateCheckoutApiV1BillingCheckoutPostResponses,
  CreateConfigApiV1WebhooksConfigsPostData,
  CreateConfigApiV1WebhooksConfigsPostErrors,
  CreateConfigApiV1WebhooksConfigsPostResponses,
  CreateFeedbackApiV1FeedbackPostData,
  CreateFeedbackApiV1FeedbackPostErrors,
  CreateFeedbackApiV1FeedbackPostResponses,
  CreateItemApiV1ItemsPostData,
  CreateItemApiV1ItemsPostErrors,
  CreateItemApiV1ItemsPostResponses,
  CreateLocationApiV1LocationsPostData,
  CreateLocationApiV1LocationsPostErrors,
  CreateLocationApiV1LocationsPostResponses,
  CreateLocationsBulkApiV1LocationsBulkPostData,
  CreateLocationsBulkApiV1LocationsBulkPostErrors,
  CreateLocationsBulkApiV1LocationsBulkPostResponses,
  CreateMyProfileApiV1ProfileMePostData,
  CreateMyProfileApiV1ProfileMePostErrors,
  CreateMyProfileApiV1ProfileMePostResponses,
  CreatePackApiV1AdminPacksPostData,
  CreatePackApiV1AdminPacksPostErrors,
  CreatePackApiV1AdminPacksPostResponses,
  CreatePlacementApiV1GridfinityUnitsUnitIdPlacementsPostData,
  CreatePlacementApiV1GridfinityUnitsUnitIdPlacementsPostErrors,
  CreatePlacementApiV1GridfinityUnitsUnitIdPlacementsPostResponses,
  CreatePortalSessionApiV1BillingPortalPostData,
  CreatePortalSessionApiV1BillingPortalPostErrors,
  CreatePortalSessionApiV1BillingPortalPostResponses,
  CreateUnitApiV1GridfinityUnitsPostData,
  CreateUnitApiV1GridfinityUnitsPostErrors,
  CreateUnitApiV1GridfinityUnitsPostResponses,
  DeclineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePostData,
  DeclineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePostErrors,
  DeclineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePostResponses,
  DeleteApiKeyApiV1AdminApikeysApiKeyIdDeleteData,
  DeleteApiKeyApiV1AdminApikeysApiKeyIdDeleteErrors,
  DeleteApiKeyApiV1AdminApikeysApiKeyIdDeleteResponses,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteData,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
  DeleteConfigApiV1WebhooksConfigsConfigIdDeleteData,
  DeleteConfigApiV1WebhooksConfigsConfigIdDeleteErrors,
  DeleteConfigApiV1WebhooksConfigsConfigIdDeleteResponses,
  DeleteFeedbackApiV1FeedbackAdminFeedbackIdDeleteData,
  DeleteFeedbackApiV1FeedbackAdminFeedbackIdDeleteErrors,
  DeleteFeedbackApiV1FeedbackAdminFeedbackIdDeleteResponses,
  DeleteImageApiV1ImagesImageIdDeleteData,
  DeleteImageApiV1ImagesImageIdDeleteErrors,
  DeleteImageApiV1ImagesImageIdDeleteResponses,
  DeleteItemApiV1ItemsItemIdDeleteData,
  DeleteItemApiV1ItemsItemIdDeleteErrors,
  DeleteItemApiV1ItemsItemIdDeleteResponses,
  DeleteLocationApiV1LocationsLocationIdDeleteData,
  DeleteLocationApiV1LocationsLocationIdDeleteErrors,
  DeleteLocationApiV1LocationsLocationIdDeleteResponses,
  DeletePackApiV1AdminPacksPackIdDeleteData,
  DeletePackApiV1AdminPacksPackIdDeleteErrors,
  DeletePackApiV1AdminPacksPackIdDeleteResponses,
  DeletePlacementApiV1GridfinityPlacementsPlacementIdDeleteData,
  DeletePlacementApiV1GridfinityPlacementsPlacementIdDeleteErrors,
  DeletePlacementApiV1GridfinityPlacementsPlacementIdDeleteResponses,
  DeleteUnitApiV1GridfinityUnitsUnitIdDeleteData,
  DeleteUnitApiV1GridfinityUnitsUnitIdDeleteErrors,
  DeleteUnitApiV1GridfinityUnitsUnitIdDeleteResponses,
  DismissRecommendationApiV1ProfileRecommendationsRecommendationIdDeleteData,
  DismissRecommendationApiV1ProfileRecommendationsRecommendationIdDeleteErrors,
  DismissRecommendationApiV1ProfileRecommendationsRecommendationIdDeleteResponses,
  FindSimilarItemsApiV1ItemsFindSimilarPostData,
  FindSimilarItemsApiV1ItemsFindSimilarPostErrors,
  FindSimilarItemsApiV1ItemsFindSimilarPostResponses,
  GenerateRecommendationsApiV1ProfileRecommendationsGeneratePostData,
  GenerateRecommendationsApiV1ProfileRecommendationsGeneratePostErrors,
  GenerateRecommendationsApiV1ProfileRecommendationsGeneratePostResponses,
  GetAllTagsApiV1ItemsTagsGetData,
  GetAllTagsApiV1ItemsTagsGetErrors,
  GetAllTagsApiV1ItemsTagsGetResponses,
  GetApiKeyApiV1AdminApikeysApiKeyIdGetData,
  GetApiKeyApiV1AdminApikeysApiKeyIdGetErrors,
  GetApiKeyApiV1AdminApikeysApiKeyIdGetResponses,
  GetAuthUrlApiV1AuthProviderGetData,
  GetAuthUrlApiV1AuthProviderGetErrors,
  GetAuthUrlApiV1AuthProviderGetResponses,
  GetBalanceApiV1BillingBalanceGetData,
  GetBalanceApiV1BillingBalanceGetErrors,
  GetBalanceApiV1BillingBalanceGetResponses,
  GetCategoryApiV1CategoriesCategoryIdGetData,
  GetCategoryApiV1CategoriesCategoryIdGetErrors,
  GetCategoryApiV1CategoriesCategoryIdGetResponses,
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetData,
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors,
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses,
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetData,
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors,
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses,
  GetCategoryTreeApiV1CategoriesTreeGetData,
  GetCategoryTreeApiV1CategoriesTreeGetErrors,
  GetCategoryTreeApiV1CategoriesTreeGetResponses,
  GetConfigApiV1WebhooksConfigsConfigIdGetData,
  GetConfigApiV1WebhooksConfigsConfigIdGetErrors,
  GetConfigApiV1WebhooksConfigsConfigIdGetResponses,
  GetCurrentUserInfoApiV1AuthMeGetData,
  GetCurrentUserInfoApiV1AuthMeGetErrors,
  GetCurrentUserInfoApiV1AuthMeGetResponses,
  GetDashboardStatsApiV1ItemsStatsDashboardGetData,
  GetDashboardStatsApiV1ItemsStatsDashboardGetErrors,
  GetDashboardStatsApiV1ItemsStatsDashboardGetResponses,
  GetFeedbackApiV1FeedbackAdminFeedbackIdGetData,
  GetFeedbackApiV1FeedbackAdminFeedbackIdGetErrors,
  GetFeedbackApiV1FeedbackAdminFeedbackIdGetResponses,
  GetHobbyTypesApiV1ProfileHobbyTypesGetData,
  GetHobbyTypesApiV1ProfileHobbyTypesGetResponses,
  GetImageApiV1ImagesImageIdGetData,
  GetImageApiV1ImagesImageIdGetErrors,
  GetImageApiV1ImagesImageIdGetResponses,
  GetImageFileApiV1ImagesImageIdFileGetData,
  GetImageFileApiV1ImagesImageIdFileGetErrors,
  GetImageFileApiV1ImagesImageIdFileGetResponses,
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetData,
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors,
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses,
  GetImageThumbnailApiV1ImagesImageIdThumbnailGetData,
  GetImageThumbnailApiV1ImagesImageIdThumbnailGetErrors,
  GetImageThumbnailApiV1ImagesImageIdThumbnailGetResponses,
  GetInventoryContextApiV1CollaborationContextGetData,
  GetInventoryContextApiV1CollaborationContextGetErrors,
  GetInventoryContextApiV1CollaborationContextGetResponses,
  GetItemApiV1ItemsItemIdGetData,
  GetItemApiV1ItemsItemIdGetErrors,
  GetItemApiV1ItemsItemIdGetResponses,
  GetItemFacetsApiV1ItemsFacetsGetData,
  GetItemFacetsApiV1ItemsFacetsGetErrors,
  GetItemFacetsApiV1ItemsFacetsGetResponses,
  GetItemHistoryApiV1ItemsItemIdHistoryGetData,
  GetItemHistoryApiV1ItemsItemIdHistoryGetErrors,
  GetItemHistoryApiV1ItemsItemIdHistoryGetResponses,
  GetItemQrCodeApiV1ItemsItemIdQrGetData,
  GetItemQrCodeApiV1ItemsItemIdQrGetErrors,
  GetItemQrCodeApiV1ItemsItemIdQrGetResponses,
  GetItemUsageStatsApiV1ItemsItemIdUsageStatsGetData,
  GetItemUsageStatsApiV1ItemsItemIdUsageStatsGetErrors,
  GetItemUsageStatsApiV1ItemsItemIdUsageStatsGetResponses,
  GetLocationApiV1LocationsLocationIdGetData,
  GetLocationApiV1LocationsLocationIdGetErrors,
  GetLocationApiV1LocationsLocationIdGetResponses,
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetData,
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors,
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses,
  GetLocationQrCodeApiV1LocationsLocationIdQrGetData,
  GetLocationQrCodeApiV1LocationsLocationIdQrGetErrors,
  GetLocationQrCodeApiV1LocationsLocationIdQrGetResponses,
  GetLocationTreeApiV1LocationsTreeGetData,
  GetLocationTreeApiV1LocationsTreeGetErrors,
  GetLocationTreeApiV1LocationsTreeGetResponses,
  GetLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGetData,
  GetLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGetErrors,
  GetLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGetResponses,
  GetMostUsedItemsApiV1ItemsStatsMostUsedGetData,
  GetMostUsedItemsApiV1ItemsStatsMostUsedGetErrors,
  GetMostUsedItemsApiV1ItemsStatsMostUsedGetResponses,
  GetMyProfileApiV1ProfileMeGetData,
  GetMyProfileApiV1ProfileMeGetErrors,
  GetMyProfileApiV1ProfileMeGetResponses,
  GetPackApiV1AdminPacksPackIdGetData,
  GetPackApiV1AdminPacksPackIdGetErrors,
  GetPackApiV1AdminPacksPackIdGetResponses,
  GetRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGetData,
  GetRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGetErrors,
  GetRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGetResponses,
  GetRecommendationsApiV1ProfileRecommendationsGetData,
  GetRecommendationsApiV1ProfileRecommendationsGetErrors,
  GetRecommendationsApiV1ProfileRecommendationsGetResponses,
  GetRecommendationsCostApiV1ProfileRecommendationsCostGetData,
  GetRecommendationsCostApiV1ProfileRecommendationsCostGetErrors,
  GetRecommendationsCostApiV1ProfileRecommendationsCostGetResponses,
  GetStatsApiV1AdminStatsGetData,
  GetStatsApiV1AdminStatsGetErrors,
  GetStatsApiV1AdminStatsGetResponses,
  GetUnitApiV1GridfinityUnitsUnitIdGetData,
  GetUnitApiV1GridfinityUnitsUnitIdGetErrors,
  GetUnitApiV1GridfinityUnitsUnitIdGetResponses,
  GetUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGetData,
  GetUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGetErrors,
  GetUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGetResponses,
  GetUserApiV1AdminUsersUserIdGetData,
  GetUserApiV1AdminUsersUserIdGetErrors,
  GetUserApiV1AdminUsersUserIdGetResponses,
  HandleWebhookApiV1BillingWebhookPostData,
  HandleWebhookApiV1BillingWebhookPostErrors,
  HandleWebhookApiV1BillingWebhookPostResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  InviteCollaboratorApiV1CollaborationCollaboratorsPostData,
  InviteCollaboratorApiV1CollaborationCollaboratorsPostErrors,
  InviteCollaboratorApiV1CollaborationCollaboratorsPostResponses,
  LeaveSharedInventoryApiV1CollaborationSharedOwnerIdDeleteData,
  LeaveSharedInventoryApiV1CollaborationSharedOwnerIdDeleteErrors,
  LeaveSharedInventoryApiV1CollaborationSharedOwnerIdDeleteResponses,
  ListAllFeedbackApiV1FeedbackAdminGetData,
  ListAllFeedbackApiV1FeedbackAdminGetErrors,
  ListAllFeedbackApiV1FeedbackAdminGetResponses,
  ListApiKeysApiV1AdminApikeysGetData,
  ListApiKeysApiV1AdminApikeysGetErrors,
  ListApiKeysApiV1AdminApikeysGetResponses,
  ListCategoriesApiV1CategoriesGetData,
  ListCategoriesApiV1CategoriesGetErrors,
  ListCategoriesApiV1CategoriesGetResponses,
  ListClassifiedImagesApiV1ImagesClassifiedGetData,
  ListClassifiedImagesApiV1ImagesClassifiedGetErrors,
  ListClassifiedImagesApiV1ImagesClassifiedGetResponses,
  ListCollaboratorsApiV1CollaborationCollaboratorsGetData,
  ListCollaboratorsApiV1CollaborationCollaboratorsGetErrors,
  ListCollaboratorsApiV1CollaborationCollaboratorsGetResponses,
  ListConfigsApiV1WebhooksConfigsGetData,
  ListConfigsApiV1WebhooksConfigsGetErrors,
  ListConfigsApiV1WebhooksConfigsGetResponses,
  ListEventTypesApiV1WebhooksEventTypesGetData,
  ListEventTypesApiV1WebhooksEventTypesGetErrors,
  ListEventTypesApiV1WebhooksEventTypesGetResponses,
  ListExecutionsApiV1WebhooksExecutionsGetData,
  ListExecutionsApiV1WebhooksExecutionsGetErrors,
  ListExecutionsApiV1WebhooksExecutionsGetResponses,
  ListItemsApiV1ItemsGetData,
  ListItemsApiV1ItemsGetErrors,
  ListItemsApiV1ItemsGetResponses,
  ListLocationsApiV1LocationsGetData,
  ListLocationsApiV1LocationsGetErrors,
  ListLocationsApiV1LocationsGetResponses,
  ListLowStockItemsApiV1ItemsLowStockGetData,
  ListLowStockItemsApiV1ItemsLowStockGetErrors,
  ListLowStockItemsApiV1ItemsLowStockGetResponses,
  ListMyFeedbackApiV1FeedbackGetData,
  ListMyFeedbackApiV1FeedbackGetErrors,
  ListMyFeedbackApiV1FeedbackGetResponses,
  ListPacksApiV1AdminPacksGetData,
  ListPacksApiV1AdminPacksGetErrors,
  ListPacksApiV1AdminPacksGetResponses,
  ListPacksApiV1BillingPacksGetData,
  ListPacksApiV1BillingPacksGetResponses,
  ListProvidersApiV1AuthProvidersGetData,
  ListProvidersApiV1AuthProvidersGetResponses,
  ListTransactionsApiV1BillingTransactionsGetData,
  ListTransactionsApiV1BillingTransactionsGetErrors,
  ListTransactionsApiV1BillingTransactionsGetResponses,
  ListUnitsApiV1GridfinityUnitsGetData,
  ListUnitsApiV1GridfinityUnitsGetErrors,
  ListUnitsApiV1GridfinityUnitsGetResponses,
  ListUsersApiV1AdminUsersGetData,
  ListUsersApiV1AdminUsersGetErrors,
  ListUsersApiV1AdminUsersGetResponses,
  MoveCategoryApiV1CategoriesCategoryIdMovePatchData,
  MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors,
  MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses,
  MoveLocationApiV1LocationsLocationIdMovePatchData,
  MoveLocationApiV1LocationsLocationIdMovePatchErrors,
  MoveLocationApiV1LocationsLocationIdMovePatchResponses,
  OauthCallbackApiV1AuthCallbackProviderGetData,
  OauthCallbackApiV1AuthCallbackProviderGetErrors,
  OauthCallbackApiV1AuthCallbackProviderGetResponses,
  QueryAssistantApiV1AiQueryPostData,
  QueryAssistantApiV1AiQueryPostErrors,
  QueryAssistantApiV1AiQueryPostResponses,
  RecommendBinSizesApiV1GridfinityRecommendBinsPostData,
  RecommendBinSizesApiV1GridfinityRecommendBinsPostErrors,
  RecommendBinSizesApiV1GridfinityRecommendBinsPostResponses,
  RefreshTokenApiV1AuthRefreshPostData,
  RefreshTokenApiV1AuthRefreshPostErrors,
  RefreshTokenApiV1AuthRefreshPostResponses,
  RemoveCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDeleteData,
  RemoveCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDeleteErrors,
  RemoveCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDeleteResponses,
  RequestRefundApiV1BillingRefundPostData,
  RequestRefundApiV1BillingRefundPostErrors,
  RequestRefundApiV1BillingRefundPostResponses,
  ResolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePutData,
  ResolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePutErrors,
  ResolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePutResponses,
  RetriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPostData,
  RetriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPostErrors,
  RetriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPostResponses,
  SearchItemsApiV1ItemsSearchGetData,
  SearchItemsApiV1ItemsSearchGetErrors,
  SearchItemsApiV1ItemsSearchGetResponses,
  SuggestItemLocationApiV1ItemsSuggestLocationPostData,
  SuggestItemLocationApiV1ItemsSuggestLocationPostErrors,
  SuggestItemLocationApiV1ItemsSuggestLocationPostResponses,
  TestConfigApiV1WebhooksConfigsConfigIdTestPostData,
  TestConfigApiV1WebhooksConfigsConfigIdTestPostErrors,
  TestConfigApiV1WebhooksConfigsConfigIdTestPostResponses,
  UpdateApiKeyApiV1AdminApikeysApiKeyIdPatchData,
  UpdateApiKeyApiV1AdminApikeysApiKeyIdPatchErrors,
  UpdateApiKeyApiV1AdminApikeysApiKeyIdPatchResponses,
  UpdateCategoryApiV1CategoriesCategoryIdPutData,
  UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
  UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
  UpdateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPutData,
  UpdateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPutErrors,
  UpdateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPutResponses,
  UpdateConfigApiV1WebhooksConfigsConfigIdPutData,
  UpdateConfigApiV1WebhooksConfigsConfigIdPutErrors,
  UpdateConfigApiV1WebhooksConfigsConfigIdPutResponses,
  UpdateFeedbackApiV1FeedbackAdminFeedbackIdPutData,
  UpdateFeedbackApiV1FeedbackAdminFeedbackIdPutErrors,
  UpdateFeedbackApiV1FeedbackAdminFeedbackIdPutResponses,
  UpdateItemApiV1ItemsItemIdPutData,
  UpdateItemApiV1ItemsItemIdPutErrors,
  UpdateItemApiV1ItemsItemIdPutResponses,
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchData,
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors,
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses,
  UpdateLocationApiV1LocationsLocationIdPutData,
  UpdateLocationApiV1LocationsLocationIdPutErrors,
  UpdateLocationApiV1LocationsLocationIdPutResponses,
  UpdateMyProfileApiV1ProfileMePatchData,
  UpdateMyProfileApiV1ProfileMePatchErrors,
  UpdateMyProfileApiV1ProfileMePatchResponses,
  UpdatePackApiV1AdminPacksPackIdPutData,
  UpdatePackApiV1AdminPacksPackIdPutErrors,
  UpdatePackApiV1AdminPacksPackIdPutResponses,
  UpdatePlacementApiV1GridfinityPlacementsPlacementIdPutData,
  UpdatePlacementApiV1GridfinityPlacementsPlacementIdPutErrors,
  UpdatePlacementApiV1GridfinityPlacementsPlacementIdPutResponses,
  UpdateRecommendationApiV1ProfileRecommendationsRecommendationIdPatchData,
  UpdateRecommendationApiV1ProfileRecommendationsRecommendationIdPatchErrors,
  UpdateRecommendationApiV1ProfileRecommendationsRecommendationIdPatchResponses,
  UpdateUnitApiV1GridfinityUnitsUnitIdPutData,
  UpdateUnitApiV1GridfinityUnitsUnitIdPutErrors,
  UpdateUnitApiV1GridfinityUnitsUnitIdPutResponses,
  UpdateUserApiV1AdminUsersUserIdPutData,
  UpdateUserApiV1AdminUsersUserIdPutErrors,
  UpdateUserApiV1AdminUsersUserIdPutResponses,
  UpdateUserSettingsApiV1AuthSettingsPatchData,
  UpdateUserSettingsApiV1AuthSettingsPatchErrors,
  UpdateUserSettingsApiV1AuthSettingsPatchResponses,
  UploadImageApiV1ImagesUploadPostData,
  UploadImageApiV1ImagesUploadPostErrors,
  UploadImageApiV1ImagesUploadPostResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * List Packs
 *
 * List all credit packs (including inactive) for admin.
 */
export const listPacksApiV1AdminPacksGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListPacksApiV1AdminPacksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPacksApiV1AdminPacksGetResponses,
    ListPacksApiV1AdminPacksGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs",
    ...options,
  });

/**
 * Create Pack
 *
 * Create a new credit pack.
 */
export const createPackApiV1AdminPacksPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreatePackApiV1AdminPacksPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreatePackApiV1AdminPacksPostResponses,
    CreatePackApiV1AdminPacksPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Pack
 *
 * Delete a credit pack (soft delete by setting inactive).
 */
export const deletePackApiV1AdminPacksPackIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePackApiV1AdminPacksPackIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeletePackApiV1AdminPacksPackIdDeleteResponses,
    DeletePackApiV1AdminPacksPackIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs/{pack_id}",
    ...options,
  });

/**
 * Get Pack
 *
 * Get a specific credit pack.
 */
export const getPackApiV1AdminPacksPackIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPackApiV1AdminPacksPackIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPackApiV1AdminPacksPackIdGetResponses,
    GetPackApiV1AdminPacksPackIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs/{pack_id}",
    ...options,
  });

/**
 * Update Pack
 *
 * Update a credit pack.
 */
export const updatePackApiV1AdminPacksPackIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePackApiV1AdminPacksPackIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdatePackApiV1AdminPacksPackIdPutResponses,
    UpdatePackApiV1AdminPacksPackIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs/{pack_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Users
 *
 * List all users with pagination.
 */
export const listUsersApiV1AdminUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUsersApiV1AdminUsersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersApiV1AdminUsersGetResponses,
    ListUsersApiV1AdminUsersGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users",
    ...options,
  });

/**
 * Get User
 *
 * Get a specific user.
 */
export const getUserApiV1AdminUsersUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserApiV1AdminUsersUserIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUserApiV1AdminUsersUserIdGetResponses,
    GetUserApiV1AdminUsersUserIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users/{user_id}",
    ...options,
  });

/**
 * Update User
 *
 * Update a user (admin status).
 */
export const updateUserApiV1AdminUsersUserIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserApiV1AdminUsersUserIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUserApiV1AdminUsersUserIdPutResponses,
    UpdateUserApiV1AdminUsersUserIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Adjust User Credits
 *
 * Grant or remove credits from a user.
 */
export const adjustUserCreditsApiV1AdminUsersUserIdCreditsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses,
    AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users/{user_id}/credits",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Stats
 *
 * Get admin dashboard statistics.
 */
export const getStatsApiV1AdminStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetStatsApiV1AdminStatsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetStatsApiV1AdminStatsGetResponses,
    GetStatsApiV1AdminStatsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/stats",
    ...options,
  });

/**
 * Query Assistant
 *
 * Query the AI assistant with a prompt.
 *
 * The assistant can provide personalized suggestions based on your inventory,
 * such as planting schedules, craft project ideas, organization tips, and more.
 *
 * Consumes 1 credit per query.
 */
export const queryAssistantApiV1AiQueryPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<QueryAssistantApiV1AiQueryPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    QueryAssistantApiV1AiQueryPostResponses,
    QueryAssistantApiV1AiQueryPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/ai/query",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Api Keys
 *
 * List all API keys for the current admin (paginated).
 */
export const listApiKeysApiV1AdminApikeysGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListApiKeysApiV1AdminApikeysGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListApiKeysApiV1AdminApikeysGetResponses,
    ListApiKeysApiV1AdminApikeysGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/apikeys",
    ...options,
  });

/**
 * Create Api Key
 *
 * Create a new API key (admin only).
 *
 * The full API key is only returned once in this response.
 * Store it securely as it cannot be retrieved again.
 */
export const createApiKeyApiV1AdminApikeysPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateApiKeyApiV1AdminApikeysPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateApiKeyApiV1AdminApikeysPostResponses,
    CreateApiKeyApiV1AdminApikeysPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/apikeys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Api Key
 *
 * Delete (revoke) an API key.
 */
export const deleteApiKeyApiV1AdminApikeysApiKeyIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteApiKeyApiV1AdminApikeysApiKeyIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteApiKeyApiV1AdminApikeysApiKeyIdDeleteResponses,
    DeleteApiKeyApiV1AdminApikeysApiKeyIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/apikeys/{api_key_id}",
    ...options,
  });

/**
 * Get Api Key
 *
 * Get details of a specific API key.
 */
export const getApiKeyApiV1AdminApikeysApiKeyIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiKeyApiV1AdminApikeysApiKeyIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiKeyApiV1AdminApikeysApiKeyIdGetResponses,
    GetApiKeyApiV1AdminApikeysApiKeyIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/apikeys/{api_key_id}",
    ...options,
  });

/**
 * Update Api Key
 *
 * Update an API key (name, scopes, or active status).
 */
export const updateApiKeyApiV1AdminApikeysApiKeyIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateApiKeyApiV1AdminApikeysApiKeyIdPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateApiKeyApiV1AdminApikeysApiKeyIdPatchResponses,
    UpdateApiKeyApiV1AdminApikeysApiKeyIdPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/apikeys/{api_key_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Providers
 *
 * List all configured OAuth providers.
 *
 * Returns providers that have valid credentials configured.
 * The frontend uses this to dynamically show login buttons.
 */
export const listProvidersApiV1AuthProvidersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListProvidersApiV1AuthProvidersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListProvidersApiV1AuthProvidersGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/auth/providers", ...options });

/**
 * Get Current User Info
 *
 * Get the current authenticated user's information.
 */
export const getCurrentUserInfoApiV1AuthMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCurrentUserInfoApiV1AuthMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCurrentUserInfoApiV1AuthMeGetResponses,
    GetCurrentUserInfoApiV1AuthMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/me",
    ...options,
  });

/**
 * Refresh Token
 *
 * Refresh the access token.
 */
export const refreshTokenApiV1AuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshTokenApiV1AuthRefreshPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    RefreshTokenApiV1AuthRefreshPostResponses,
    RefreshTokenApiV1AuthRefreshPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/refresh",
    ...options,
  });

/**
 * Update User Settings
 *
 * Update the current user's settings.
 */
export const updateUserSettingsApiV1AuthSettingsPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserSettingsApiV1AuthSettingsPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateUserSettingsApiV1AuthSettingsPatchResponses,
    UpdateUserSettingsApiV1AuthSettingsPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Oauth Callback
 *
 * Handle OAuth callback for any configured provider.
 *
 * Exchange the authorization code for tokens and create/get user.
 */
export const oauthCallbackApiV1AuthCallbackProviderGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OauthCallbackApiV1AuthCallbackProviderGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    OauthCallbackApiV1AuthCallbackProviderGetResponses,
    OauthCallbackApiV1AuthCallbackProviderGetErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/callback/{provider}", ...options });

/**
 * Get Auth Url
 *
 * Get OAuth authorization URL for any configured provider.
 *
 * The client should redirect to this URL to initiate OAuth flow.
 */
export const getAuthUrlApiV1AuthProviderGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAuthUrlApiV1AuthProviderGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAuthUrlApiV1AuthProviderGetResponses,
    GetAuthUrlApiV1AuthProviderGetErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/{provider}", ...options });

/**
 * Get Balance
 *
 * Get current credit balance for the authenticated user.
 */
export const getBalanceApiV1BillingBalanceGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetBalanceApiV1BillingBalanceGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetBalanceApiV1BillingBalanceGetResponses,
    GetBalanceApiV1BillingBalanceGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/balance",
    ...options,
  });

/**
 * List Packs
 *
 * List all available credit packs.
 */
export const listPacksApiV1BillingPacksGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListPacksApiV1BillingPacksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPacksApiV1BillingPacksGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/billing/packs", ...options });

/**
 * Create Checkout
 *
 * Create a Stripe checkout session for purchasing credits.
 */
export const createCheckoutApiV1BillingCheckoutPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCheckoutApiV1BillingCheckoutPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCheckoutApiV1BillingCheckoutPostResponses,
    CreateCheckoutApiV1BillingCheckoutPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/checkout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Transactions
 *
 * Get transaction history for the authenticated user.
 */
export const listTransactionsApiV1BillingTransactionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListTransactionsApiV1BillingTransactionsGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListTransactionsApiV1BillingTransactionsGetResponses,
    ListTransactionsApiV1BillingTransactionsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/transactions",
    ...options,
  });

/**
 * Create Portal Session
 *
 * Create a Stripe customer portal session.
 */
export const createPortalSessionApiV1BillingPortalPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CreatePortalSessionApiV1BillingPortalPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    CreatePortalSessionApiV1BillingPortalPostResponses,
    CreatePortalSessionApiV1BillingPortalPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/portal",
    ...options,
  });

/**
 * Request Refund
 *
 * Request a refund for an unused credit purchase.
 */
export const requestRefundApiV1BillingRefundPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RequestRefundApiV1BillingRefundPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RequestRefundApiV1BillingRefundPostResponses,
    RequestRefundApiV1BillingRefundPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/refund",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Handle Webhook
 *
 * Handle Stripe webhook events.
 */
export const handleWebhookApiV1BillingWebhookPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<HandleWebhookApiV1BillingWebhookPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    HandleWebhookApiV1BillingWebhookPostResponses,
    HandleWebhookApiV1BillingWebhookPostErrors,
    ThrowOnError
  >({ url: "/api/v1/billing/webhook", ...options });

/**
 * List My Feedback
 *
 * List feedback submitted by the current user.
 */
export const listMyFeedbackApiV1FeedbackGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListMyFeedbackApiV1FeedbackGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListMyFeedbackApiV1FeedbackGetResponses,
    ListMyFeedbackApiV1FeedbackGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback",
    ...options,
  });

/**
 * Create Feedback
 *
 * Submit feedback.
 */
export const createFeedbackApiV1FeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFeedbackApiV1FeedbackPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateFeedbackApiV1FeedbackPostResponses,
    CreateFeedbackApiV1FeedbackPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List All Feedback
 *
 * List all feedback (admin only).
 */
export const listAllFeedbackApiV1FeedbackAdminGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAllFeedbackApiV1FeedbackAdminGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListAllFeedbackApiV1FeedbackAdminGetResponses,
    ListAllFeedbackApiV1FeedbackAdminGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback/admin",
    ...options,
  });

/**
 * Delete Feedback
 *
 * Delete feedback (admin only).
 */
export const deleteFeedbackApiV1FeedbackAdminFeedbackIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteFeedbackApiV1FeedbackAdminFeedbackIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteFeedbackApiV1FeedbackAdminFeedbackIdDeleteResponses,
    DeleteFeedbackApiV1FeedbackAdminFeedbackIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback/admin/{feedback_id}",
    ...options,
  });

/**
 * Get Feedback
 *
 * Get specific feedback (admin only).
 */
export const getFeedbackApiV1FeedbackAdminFeedbackIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFeedbackApiV1FeedbackAdminFeedbackIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetFeedbackApiV1FeedbackAdminFeedbackIdGetResponses,
    GetFeedbackApiV1FeedbackAdminFeedbackIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback/admin/{feedback_id}",
    ...options,
  });

/**
 * Update Feedback
 *
 * Update feedback status/notes (admin only).
 */
export const updateFeedbackApiV1FeedbackAdminFeedbackIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateFeedbackApiV1FeedbackAdminFeedbackIdPutData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    UpdateFeedbackApiV1FeedbackAdminFeedbackIdPutResponses,
    UpdateFeedbackApiV1FeedbackAdminFeedbackIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback/admin/{feedback_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Resolve Feedback
 *
 * Mark feedback as resolved.
 *
 * This endpoint accepts both Bearer token (admin) and API key authentication.
 * For API key auth, the key must have the 'feedback:write' scope.
 */
export const resolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ResolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePutData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ResolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePutResponses,
    ResolveFeedbackApiV1FeedbackAdminFeedbackIdResolvePutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/feedback/admin/{feedback_id}/resolve",
    ...options,
  });

/**
 * Retrigger Feedback Webhook
 *
 * Re-trigger the feedback.created webhook for a specific feedback item (admin only).
 */
export const retriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RetriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPostData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).post<
      RetriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPostResponses,
      RetriggerFeedbackWebhookApiV1FeedbackAdminFeedbackIdRetriggerWebhookPostErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/feedback/admin/{feedback_id}/retrigger-webhook",
      ...options,
    });

/**
 * List Items
 *
 * List items with filtering and pagination.
 *
 * When filtering by category or location, child categories/locations are included by default.
 * Set include_subcategories=false or include_sublocations=false to filter by exact match only.
 *
 * Use no_category=true to filter items without any category assigned.
 * Use no_location=true to filter items without any location assigned.
 * Use checked_out=true to filter items that are currently checked out.
 *
 * Filter by tags using ?tags=tag1&tags=tag2 (items must have ALL specified tags).
 * Filter by attributes using ?attr=key1:value1&attr=key2:value2.
 */
export const listItemsApiV1ItemsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListItemsApiV1ItemsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListItemsApiV1ItemsGetResponses,
    ListItemsApiV1ItemsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items",
    ...options,
  });

/**
 * Create Item
 *
 * Create a new item.
 */
export const createItemApiV1ItemsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemApiV1ItemsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateItemApiV1ItemsPostResponses,
    CreateItemApiV1ItemsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Batch Update Items
 *
 * Batch update multiple items with the same category and/or location.
 *
 * Use this endpoint to assign a category or location to multiple items at once.
 * You can also use clear_category=true or clear_location=true to remove
 * the category or location from the selected items.
 */
export const batchUpdateItemsApiV1ItemsBatchPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<BatchUpdateItemsApiV1ItemsBatchPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    BatchUpdateItemsApiV1ItemsBatchPatchResponses,
    BatchUpdateItemsApiV1ItemsBatchPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/batch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Dashboard Stats
 *
 * Get dashboard statistics including time series data.
 */
export const getDashboardStatsApiV1ItemsStatsDashboardGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetDashboardStatsApiV1ItemsStatsDashboardGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetDashboardStatsApiV1ItemsStatsDashboardGetResponses,
    GetDashboardStatsApiV1ItemsStatsDashboardGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/stats/dashboard",
    ...options,
  });

/**
 * Get Most Used Items
 *
 * Get items with most check-outs for dashboard.
 */
export const getMostUsedItemsApiV1ItemsStatsMostUsedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetMostUsedItemsApiV1ItemsStatsMostUsedGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetMostUsedItemsApiV1ItemsStatsMostUsedGetResponses,
    GetMostUsedItemsApiV1ItemsStatsMostUsedGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/stats/most-used",
    ...options,
  });

/**
 * Get Recently Used Items
 *
 * Get items with most recent check-in/out activity.
 */
export const getRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGetResponses,
    GetRecentlyUsedItemsApiV1ItemsStatsRecentlyUsedGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/stats/recently-used",
    ...options,
  });

/**
 * Search Items
 *
 * Search items by name, description, or tags.
 */
export const searchItemsApiV1ItemsSearchGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SearchItemsApiV1ItemsSearchGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SearchItemsApiV1ItemsSearchGetResponses,
    SearchItemsApiV1ItemsSearchGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/search",
    ...options,
  });

/**
 * Find Similar Items
 *
 * Find items similar to a classification result.
 *
 * Use this endpoint after AI classification to check for potential duplicates
 * before creating a new item. Returns items sorted by similarity score.
 */
export const findSimilarItemsApiV1ItemsFindSimilarPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FindSimilarItemsApiV1ItemsFindSimilarPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    FindSimilarItemsApiV1ItemsFindSimilarPostResponses,
    FindSimilarItemsApiV1ItemsFindSimilarPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/find-similar",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Suggest Item Location
 *
 * Suggest optimal storage locations for an item using AI.
 *
 * Analyzes the item's characteristics and the user's existing locations
 * with their stored items to recommend suitable storage places.
 *
 * Consumes 1 credit on successful suggestion.
 */
export const suggestItemLocationApiV1ItemsSuggestLocationPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SuggestItemLocationApiV1ItemsSuggestLocationPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    SuggestItemLocationApiV1ItemsSuggestLocationPostResponses,
    SuggestItemLocationApiV1ItemsSuggestLocationPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/suggest-location",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Low Stock Items
 *
 * List items that are below their minimum quantity threshold.
 */
export const listLowStockItemsApiV1ItemsLowStockGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListLowStockItemsApiV1ItemsLowStockGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListLowStockItemsApiV1ItemsLowStockGetResponses,
    ListLowStockItemsApiV1ItemsLowStockGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/low-stock",
    ...options,
  });

/**
 * Get Item Facets
 *
 * Get available facets (attribute values with counts) for filtering.
 *
 * Facets are based on the category's attribute template if a category is specified,
 * or all unique attribute keys found in matching items.
 */
export const getItemFacetsApiV1ItemsFacetsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetItemFacetsApiV1ItemsFacetsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetItemFacetsApiV1ItemsFacetsGetResponses,
    GetItemFacetsApiV1ItemsFacetsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/facets",
    ...options,
  });

/**
 * Get All Tags
 *
 * Get all unique tags with their counts.
 */
export const getAllTagsApiV1ItemsTagsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllTagsApiV1ItemsTagsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetAllTagsApiV1ItemsTagsGetResponses,
    GetAllTagsApiV1ItemsTagsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/tags",
    ...options,
  });

/**
 * Delete Item
 *
 * Delete an item.
 */
export const deleteItemApiV1ItemsItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemApiV1ItemsItemIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteItemApiV1ItemsItemIdDeleteResponses,
    DeleteItemApiV1ItemsItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}",
    ...options,
  });

/**
 * Get Item
 *
 * Get an item by ID.
 */
export const getItemApiV1ItemsItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemApiV1ItemsItemIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetItemApiV1ItemsItemIdGetResponses,
    GetItemApiV1ItemsItemIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}",
    ...options,
  });

/**
 * Update Item
 *
 * Update an item.
 */
export const updateItemApiV1ItemsItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateItemApiV1ItemsItemIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateItemApiV1ItemsItemIdPutResponses,
    UpdateItemApiV1ItemsItemIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Item Qr Code
 *
 * Generate a QR code PNG for an item.
 *
 * The QR code contains the item's URL for scanning.
 */
export const getItemQrCodeApiV1ItemsItemIdQrGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemQrCodeApiV1ItemsItemIdQrGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetItemQrCodeApiV1ItemsItemIdQrGetResponses,
    GetItemQrCodeApiV1ItemsItemIdQrGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/qr",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Item Quantity
 *
 * Quick update for item quantity.
 */
export const updateItemQuantityApiV1ItemsItemIdQuantityPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateItemQuantityApiV1ItemsItemIdQuantityPatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses,
    UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/quantity",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Check Out Item
 *
 * Record a check-out event for an item.
 *
 * Uses row-level locking to prevent race conditions where concurrent
 * check-outs could exceed the available quantity.
 */
export const checkOutItemApiV1ItemsItemIdCheckOutPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CheckOutItemApiV1ItemsItemIdCheckOutPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CheckOutItemApiV1ItemsItemIdCheckOutPostResponses,
    CheckOutItemApiV1ItemsItemIdCheckOutPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/check-out",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Check In Item
 *
 * Record a check-in event for an item.
 *
 * Uses row-level locking to prevent race conditions where concurrent
 * check-ins could result in negative 'currently out' counts.
 */
export const checkInItemApiV1ItemsItemIdCheckInPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CheckInItemApiV1ItemsItemIdCheckInPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CheckInItemApiV1ItemsItemIdCheckInPostResponses,
    CheckInItemApiV1ItemsItemIdCheckInPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/check-in",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Item History
 *
 * Get check-in/out history for an item.
 */
export const getItemHistoryApiV1ItemsItemIdHistoryGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemHistoryApiV1ItemsItemIdHistoryGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetItemHistoryApiV1ItemsItemIdHistoryGetResponses,
    GetItemHistoryApiV1ItemsItemIdHistoryGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/history",
    ...options,
  });

/**
 * Get Item Usage Stats
 *
 * Get usage statistics for an item.
 */
export const getItemUsageStatsApiV1ItemsItemIdUsageStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetItemUsageStatsApiV1ItemsItemIdUsageStatsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetItemUsageStatsApiV1ItemsItemIdUsageStatsGetResponses,
    GetItemUsageStatsApiV1ItemsItemIdUsageStatsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/usage-stats",
    ...options,
  });

/**
 * List Categories
 *
 * List all categories for the inventory context, ordered by hierarchy path.
 */
export const listCategoriesApiV1CategoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCategoriesApiV1CategoriesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListCategoriesApiV1CategoriesGetResponses,
    ListCategoriesApiV1CategoriesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories",
    ...options,
  });

/**
 * Create Category
 *
 * Create a new category.
 */
export const createCategoryApiV1CategoriesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCategoryApiV1CategoriesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCategoryApiV1CategoriesPostResponses,
    CreateCategoryApiV1CategoriesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Category Tree
 *
 * Get categories as a nested tree structure with item counts.
 */
export const getCategoryTreeApiV1CategoriesTreeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCategoryTreeApiV1CategoriesTreeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCategoryTreeApiV1CategoriesTreeGetResponses,
    GetCategoryTreeApiV1CategoriesTreeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/tree",
    ...options,
  });

/**
 * Create Category From Path
 *
 * Create categories from an AI-suggested path.
 *
 * Parses a path like 'Hardware > Fasteners > Screws' and creates any
 * missing categories in the hierarchy. Returns the leaf category.
 */
export const createCategoryFromPathApiV1CategoriesFromPathPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateCategoryFromPathApiV1CategoriesFromPathPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateCategoryFromPathApiV1CategoriesFromPathPostResponses,
    CreateCategoryFromPathApiV1CategoriesFromPathPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/from-path",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Category
 *
 * Delete a category. Child categories will become root-level categories.
 */
export const deleteCategoryApiV1CategoriesCategoryIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCategoryApiV1CategoriesCategoryIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
    DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}",
    ...options,
  });

/**
 * Get Category
 *
 * Get a category by ID.
 */
export const getCategoryApiV1CategoriesCategoryIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCategoryApiV1CategoriesCategoryIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCategoryApiV1CategoriesCategoryIdGetResponses,
    GetCategoryApiV1CategoriesCategoryIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}",
    ...options,
  });

/**
 * Update Category
 *
 * Update a category.
 */
export const updateCategoryApiV1CategoriesCategoryIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCategoryApiV1CategoriesCategoryIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
    UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Category Template
 *
 * Get merged attribute template for a category.
 *
 * Returns fields from this category and all ancestors, with child fields
 * overriding parent fields of the same name.
 */
export const getCategoryTemplateApiV1CategoriesCategoryIdTemplateGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses,
    GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}/template",
    ...options,
  });

/**
 * Get Category Descendants
 *
 * Get all descendant categories of a category.
 */
export const getCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses,
    GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}/descendants",
    ...options,
  });

/**
 * Move Category
 *
 * Move a category to a new parent (or to root level if new_parent_id is null).
 */
export const moveCategoryApiV1CategoriesCategoryIdMovePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    MoveCategoryApiV1CategoriesCategoryIdMovePatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses,
    MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Locations
 *
 * List all locations for the inventory context, ordered by hierarchy path.
 */
export const listLocationsApiV1LocationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListLocationsApiV1LocationsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListLocationsApiV1LocationsGetResponses,
    ListLocationsApiV1LocationsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations",
    ...options,
  });

/**
 * Create Location
 *
 * Create a new location.
 */
export const createLocationApiV1LocationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateLocationApiV1LocationsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateLocationApiV1LocationsPostResponses,
    CreateLocationApiV1LocationsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Location Tree
 *
 * Get locations as a nested tree structure with item counts.
 */
export const getLocationTreeApiV1LocationsTreeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetLocationTreeApiV1LocationsTreeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetLocationTreeApiV1LocationsTreeGetResponses,
    GetLocationTreeApiV1LocationsTreeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/tree",
    ...options,
  });

/**
 * Analyze Location Image
 *
 * Analyze an image to suggest location structure using AI.
 *
 * Consumes 1 credit on successful analysis.
 */
export const analyzeLocationImageApiV1LocationsAnalyzeImagePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AnalyzeLocationImageApiV1LocationsAnalyzeImagePostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AnalyzeLocationImageApiV1LocationsAnalyzeImagePostResponses,
    AnalyzeLocationImageApiV1LocationsAnalyzeImagePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/analyze-image",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Locations Bulk
 *
 * Create a parent location with multiple children in a single operation.
 */
export const createLocationsBulkApiV1LocationsBulkPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateLocationsBulkApiV1LocationsBulkPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateLocationsBulkApiV1LocationsBulkPostResponses,
    CreateLocationsBulkApiV1LocationsBulkPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/bulk",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Location
 *
 * Delete a location. Child locations will become root-level locations.
 */
export const deleteLocationApiV1LocationsLocationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteLocationApiV1LocationsLocationIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteLocationApiV1LocationsLocationIdDeleteResponses,
    DeleteLocationApiV1LocationsLocationIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}",
    ...options,
  });

/**
 * Get Location
 *
 * Get a location by ID.
 */
export const getLocationApiV1LocationsLocationIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLocationApiV1LocationsLocationIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLocationApiV1LocationsLocationIdGetResponses,
    GetLocationApiV1LocationsLocationIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}",
    ...options,
  });

/**
 * Update Location
 *
 * Update a location.
 */
export const updateLocationApiV1LocationsLocationIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateLocationApiV1LocationsLocationIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateLocationApiV1LocationsLocationIdPutResponses,
    UpdateLocationApiV1LocationsLocationIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Location Descendants
 *
 * Get all descendant locations of a location.
 */
export const getLocationDescendantsApiV1LocationsLocationIdDescendantsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses,
    GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}/descendants",
    ...options,
  });

/**
 * Move Location
 *
 * Move a location to a new parent (or to root level if new_parent_id is null).
 */
export const moveLocationApiV1LocationsLocationIdMovePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    MoveLocationApiV1LocationsLocationIdMovePatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    MoveLocationApiV1LocationsLocationIdMovePatchResponses,
    MoveLocationApiV1LocationsLocationIdMovePatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Location With Ancestors
 *
 * Get a location with its full ancestor path for breadcrumb navigation.
 */
export const getLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGetData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).get<
      GetLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGetResponses,
      GetLocationWithAncestorsApiV1LocationsLocationIdWithAncestorsGetErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/locations/{location_id}/with-ancestors",
      ...options,
    });

/**
 * Get Location Qr Code
 *
 * Generate a QR code PNG for a location.
 *
 * The QR code contains the location's URL for scanning.
 */
export const getLocationQrCodeApiV1LocationsLocationIdQrGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetLocationQrCodeApiV1LocationsLocationIdQrGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetLocationQrCodeApiV1LocationsLocationIdQrGetResponses,
    GetLocationQrCodeApiV1LocationsLocationIdQrGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}/qr",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Units
 *
 * List all Gridfinity storage units for the current user.
 */
export const listUnitsApiV1GridfinityUnitsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUnitsApiV1GridfinityUnitsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUnitsApiV1GridfinityUnitsGetResponses,
    ListUnitsApiV1GridfinityUnitsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units",
    ...options,
  });

/**
 * Create Unit
 *
 * Create a new Gridfinity storage unit.
 */
export const createUnitApiV1GridfinityUnitsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUnitApiV1GridfinityUnitsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUnitApiV1GridfinityUnitsPostResponses,
    CreateUnitApiV1GridfinityUnitsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Unit
 *
 * Delete a Gridfinity unit and all its placements.
 */
export const deleteUnitApiV1GridfinityUnitsUnitIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteUnitApiV1GridfinityUnitsUnitIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUnitApiV1GridfinityUnitsUnitIdDeleteResponses,
    DeleteUnitApiV1GridfinityUnitsUnitIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units/{unit_id}",
    ...options,
  });

/**
 * Get Unit
 *
 * Get a Gridfinity unit by ID.
 */
export const getUnitApiV1GridfinityUnitsUnitIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUnitApiV1GridfinityUnitsUnitIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUnitApiV1GridfinityUnitsUnitIdGetResponses,
    GetUnitApiV1GridfinityUnitsUnitIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units/{unit_id}",
    ...options,
  });

/**
 * Update Unit
 *
 * Update a Gridfinity unit.
 */
export const updateUnitApiV1GridfinityUnitsUnitIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUnitApiV1GridfinityUnitsUnitIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUnitApiV1GridfinityUnitsUnitIdPutResponses,
    UpdateUnitApiV1GridfinityUnitsUnitIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units/{unit_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Unit Layout
 *
 * Get a Gridfinity unit with all placements for rendering the layout.
 */
export const getUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGetResponses,
    GetUnitLayoutApiV1GridfinityUnitsUnitIdLayoutGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units/{unit_id}/layout",
    ...options,
  });

/**
 * Create Placement
 *
 * Add an item placement to a Gridfinity unit.
 */
export const createPlacementApiV1GridfinityUnitsUnitIdPlacementsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreatePlacementApiV1GridfinityUnitsUnitIdPlacementsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreatePlacementApiV1GridfinityUnitsUnitIdPlacementsPostResponses,
    CreatePlacementApiV1GridfinityUnitsUnitIdPlacementsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units/{unit_id}/placements",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Placement
 *
 * Remove an item placement from a unit.
 */
export const deletePlacementApiV1GridfinityPlacementsPlacementIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeletePlacementApiV1GridfinityPlacementsPlacementIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeletePlacementApiV1GridfinityPlacementsPlacementIdDeleteResponses,
    DeletePlacementApiV1GridfinityPlacementsPlacementIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/placements/{placement_id}",
    ...options,
  });

/**
 * Update Placement
 *
 * Update a placement (move or resize).
 */
export const updatePlacementApiV1GridfinityPlacementsPlacementIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdatePlacementApiV1GridfinityPlacementsPlacementIdPutData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    UpdatePlacementApiV1GridfinityPlacementsPlacementIdPutResponses,
    UpdatePlacementApiV1GridfinityPlacementsPlacementIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/placements/{placement_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Auto Layout Items
 *
 * Automatically arrange items in a unit using bin-packing algorithm.
 */
export const autoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AutoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AutoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPostResponses,
    AutoLayoutItemsApiV1GridfinityUnitsUnitIdAutoLayoutPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/units/{unit_id}/auto-layout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Recommend Bin Sizes
 *
 * Get bin size recommendations for items based on their dimensions.
 */
export const recommendBinSizesApiV1GridfinityRecommendBinsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RecommendBinSizesApiV1GridfinityRecommendBinsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    RecommendBinSizesApiV1GridfinityRecommendBinsPostResponses,
    RecommendBinSizesApiV1GridfinityRecommendBinsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gridfinity/recommend-bins",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Calculate Grid
 *
 * Calculate grid size from container dimensions.
 *
 * Returns the number of columns and rows that fit, plus wasted space.
 */
export const calculateGridApiV1GridfinityCalculateGridGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CalculateGridApiV1GridfinityCalculateGridGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    CalculateGridApiV1GridfinityCalculateGridGetResponses,
    CalculateGridApiV1GridfinityCalculateGridGetErrors,
    ThrowOnError
  >({ url: "/api/v1/gridfinity/calculate-grid", ...options });

/**
 * Upload Image
 *
 * Upload an image file.
 *
 * If the same image content was previously uploaded by this user,
 * returns the existing image record instead of creating a duplicate.
 */
export const uploadImageApiV1ImagesUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UploadImageApiV1ImagesUploadPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadImageApiV1ImagesUploadPostResponses,
    UploadImageApiV1ImagesUploadPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Classify Image
 *
 * Classify an uploaded image using AI.
 */
export const classifyImageApiV1ImagesClassifyPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ClassifyImageApiV1ImagesClassifyPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ClassifyImageApiV1ImagesClassifyPostResponses,
    ClassifyImageApiV1ImagesClassifyPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/classify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Classified Images
 *
 * List all images that have been classified by AI.
 *
 * Supports optional search by the identified item name (case-insensitive partial match).
 */
export const listClassifiedImagesApiV1ImagesClassifiedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListClassifiedImagesApiV1ImagesClassifiedGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListClassifiedImagesApiV1ImagesClassifiedGetResponses,
    ListClassifiedImagesApiV1ImagesClassifiedGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/classified",
    ...options,
  });

/**
 * Delete Image
 *
 * Delete an image.
 */
export const deleteImageApiV1ImagesImageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteImageApiV1ImagesImageIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteImageApiV1ImagesImageIdDeleteResponses,
    DeleteImageApiV1ImagesImageIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}",
    ...options,
  });

/**
 * Get Image
 *
 * Get image metadata.
 */
export const getImageApiV1ImagesImageIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetImageApiV1ImagesImageIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetImageApiV1ImagesImageIdGetResponses,
    GetImageApiV1ImagesImageIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}",
    ...options,
  });

/**
 * Get Image Signed Url
 *
 * Get a signed URL for accessing an image file.
 *
 * This generates a short-lived token that can be used in browser <img> tags
 * where Authorization headers cannot be sent.
 *
 * Set thumbnail=true to get a URL for the thumbnail version.
 *
 * Supports collaboration: when viewing a shared inventory, the signed URL
 * will be generated for the inventory owner's images.
 */
export const getImageSignedUrlApiV1ImagesImageIdSignedUrlGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses,
    GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}/signed-url",
    ...options,
  });

/**
 * Get Image File
 *
 * Get the actual image file.
 *
 * Requires a valid signed token query parameter for authentication.
 * Use GET /{image_id}/signed-url to obtain a token.
 */
export const getImageFileApiV1ImagesImageIdFileGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetImageFileApiV1ImagesImageIdFileGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetImageFileApiV1ImagesImageIdFileGetResponses,
    GetImageFileApiV1ImagesImageIdFileGetErrors,
    ThrowOnError
  >({ url: "/api/v1/images/{image_id}/file", ...options });

/**
 * Get Image Thumbnail
 *
 * Get the thumbnail image file.
 *
 * Requires a valid signed token query parameter for authentication.
 * Use GET /{image_id}/signed-url?thumbnail=true to obtain a token.
 * Falls back to the original image if no thumbnail exists.
 */
export const getImageThumbnailApiV1ImagesImageIdThumbnailGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetImageThumbnailApiV1ImagesImageIdThumbnailGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetImageThumbnailApiV1ImagesImageIdThumbnailGetResponses,
    GetImageThumbnailApiV1ImagesImageIdThumbnailGetErrors,
    ThrowOnError
  >({ url: "/api/v1/images/{image_id}/thumbnail", ...options });

/**
 * Attach Image To Item
 *
 * Attach an image to an item.
 */
export const attachImageToItemApiV1ImagesImageIdAttachItemIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AttachImageToItemApiV1ImagesImageIdAttachItemIdPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses,
    AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}/attach/{item_id}",
    ...options,
  });

/**
 * Get Hobby Types
 *
 * Get list of available hobby types.
 */
export const getHobbyTypesApiV1ProfileHobbyTypesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetHobbyTypesApiV1ProfileHobbyTypesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetHobbyTypesApiV1ProfileHobbyTypesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/profile/hobby-types", ...options });

/**
 * Get My Profile
 *
 * Get the current user's system profile.
 */
export const getMyProfileApiV1ProfileMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyProfileApiV1ProfileMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetMyProfileApiV1ProfileMeGetResponses,
    GetMyProfileApiV1ProfileMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/profile/me",
    ...options,
  });

/**
 * Update My Profile
 *
 * Update the current user's system profile.
 */
export const updateMyProfileApiV1ProfileMePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMyProfileApiV1ProfileMePatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateMyProfileApiV1ProfileMePatchResponses,
    UpdateMyProfileApiV1ProfileMePatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/profile/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create My Profile
 *
 * Create or update the current user's system profile.
 */
export const createMyProfileApiV1ProfileMePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMyProfileApiV1ProfileMePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateMyProfileApiV1ProfileMePostResponses,
    CreateMyProfileApiV1ProfileMePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/profile/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Recommendations
 *
 * Get pending purge recommendations for the current user.
 */
export const getRecommendationsApiV1ProfileRecommendationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetRecommendationsApiV1ProfileRecommendationsGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetRecommendationsApiV1ProfileRecommendationsGetResponses,
    GetRecommendationsApiV1ProfileRecommendationsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/profile/recommendations",
    ...options,
  });

/**
 * Get Recommendations Cost
 *
 * Get the cost estimate for generating declutter suggestions.
 *
 * Returns the number of credits required based on items to analyze.
 * Cost is 1 credit per 50 items, with a minimum of 1 credit.
 */
export const getRecommendationsCostApiV1ProfileRecommendationsCostGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetRecommendationsCostApiV1ProfileRecommendationsCostGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetRecommendationsCostApiV1ProfileRecommendationsCostGetResponses,
    GetRecommendationsCostApiV1ProfileRecommendationsCostGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/profile/recommendations/cost",
    ...options,
  });

/**
 * Generate Recommendations
 *
 * Generate new declutter suggestions using AI.
 *
 * Credit cost is based on items_to_analyze: 1 credit per 50 items (minimum 1).
 */
export const generateRecommendationsApiV1ProfileRecommendationsGeneratePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GenerateRecommendationsApiV1ProfileRecommendationsGeneratePostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    GenerateRecommendationsApiV1ProfileRecommendationsGeneratePostResponses,
    GenerateRecommendationsApiV1ProfileRecommendationsGeneratePostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/profile/recommendations/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Dismiss Recommendation
 *
 * Dismiss a purge recommendation (shortcut for updating status to 'dismissed').
 */
export const dismissRecommendationApiV1ProfileRecommendationsRecommendationIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DismissRecommendationApiV1ProfileRecommendationsRecommendationIdDeleteData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).delete<
      DismissRecommendationApiV1ProfileRecommendationsRecommendationIdDeleteResponses,
      DismissRecommendationApiV1ProfileRecommendationsRecommendationIdDeleteErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/profile/recommendations/{recommendation_id}",
      ...options,
    });

/**
 * Update Recommendation
 *
 * Accept or dismiss a purge recommendation.
 */
export const updateRecommendationApiV1ProfileRecommendationsRecommendationIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateRecommendationApiV1ProfileRecommendationsRecommendationIdPatchData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).patch<
      UpdateRecommendationApiV1ProfileRecommendationsRecommendationIdPatchResponses,
      UpdateRecommendationApiV1ProfileRecommendationsRecommendationIdPatchErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/profile/recommendations/{recommendation_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * List Event Types
 *
 * List available event types for webhooks.
 */
export const listEventTypesApiV1WebhooksEventTypesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListEventTypesApiV1WebhooksEventTypesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListEventTypesApiV1WebhooksEventTypesGetResponses,
    ListEventTypesApiV1WebhooksEventTypesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/event-types",
    ...options,
  });

/**
 * List Configs
 *
 * List all webhook configurations.
 */
export const listConfigsApiV1WebhooksConfigsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListConfigsApiV1WebhooksConfigsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListConfigsApiV1WebhooksConfigsGetResponses,
    ListConfigsApiV1WebhooksConfigsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/configs",
    ...options,
  });

/**
 * Create Config
 *
 * Create a new webhook configuration.
 */
export const createConfigApiV1WebhooksConfigsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateConfigApiV1WebhooksConfigsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateConfigApiV1WebhooksConfigsPostResponses,
    CreateConfigApiV1WebhooksConfigsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/configs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Config
 *
 * Delete a webhook configuration.
 */
export const deleteConfigApiV1WebhooksConfigsConfigIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteConfigApiV1WebhooksConfigsConfigIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteConfigApiV1WebhooksConfigsConfigIdDeleteResponses,
    DeleteConfigApiV1WebhooksConfigsConfigIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/configs/{config_id}",
    ...options,
  });

/**
 * Get Config
 *
 * Get a specific webhook configuration.
 */
export const getConfigApiV1WebhooksConfigsConfigIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetConfigApiV1WebhooksConfigsConfigIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetConfigApiV1WebhooksConfigsConfigIdGetResponses,
    GetConfigApiV1WebhooksConfigsConfigIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/configs/{config_id}",
    ...options,
  });

/**
 * Update Config
 *
 * Update a webhook configuration.
 */
export const updateConfigApiV1WebhooksConfigsConfigIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateConfigApiV1WebhooksConfigsConfigIdPutData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    UpdateConfigApiV1WebhooksConfigsConfigIdPutResponses,
    UpdateConfigApiV1WebhooksConfigsConfigIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/configs/{config_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Test Config
 *
 * Test a webhook configuration with sample data.
 */
export const testConfigApiV1WebhooksConfigsConfigIdTestPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TestConfigApiV1WebhooksConfigsConfigIdTestPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    TestConfigApiV1WebhooksConfigsConfigIdTestPostResponses,
    TestConfigApiV1WebhooksConfigsConfigIdTestPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/configs/{config_id}/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Executions
 *
 * List webhook execution logs.
 */
export const listExecutionsApiV1WebhooksExecutionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListExecutionsApiV1WebhooksExecutionsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListExecutionsApiV1WebhooksExecutionsGetResponses,
    ListExecutionsApiV1WebhooksExecutionsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/webhooks/executions",
    ...options,
  });

/**
 * Get Inventory Context
 *
 * Get the user's inventory context including own and shared inventories.
 */
export const getInventoryContextApiV1CollaborationContextGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetInventoryContextApiV1CollaborationContextGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetInventoryContextApiV1CollaborationContextGetResponses,
    GetInventoryContextApiV1CollaborationContextGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/collaboration/context",
    ...options,
  });

/**
 * List Collaborators
 *
 * List all collaborators for the current user's inventory.
 */
export const listCollaboratorsApiV1CollaborationCollaboratorsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListCollaboratorsApiV1CollaborationCollaboratorsGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListCollaboratorsApiV1CollaborationCollaboratorsGetResponses,
    ListCollaboratorsApiV1CollaborationCollaboratorsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/collaboration/collaborators",
    ...options,
  });

/**
 * Invite Collaborator
 *
 * Invite a new collaborator to the inventory.
 */
export const inviteCollaboratorApiV1CollaborationCollaboratorsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    InviteCollaboratorApiV1CollaborationCollaboratorsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    InviteCollaboratorApiV1CollaborationCollaboratorsPostResponses,
    InviteCollaboratorApiV1CollaborationCollaboratorsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/collaboration/collaborators",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Collaborator
 *
 * Remove a collaborator from the inventory.
 */
export const removeCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDeleteData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).delete<
      RemoveCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDeleteResponses,
      RemoveCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdDeleteErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/collaboration/collaborators/{collaborator_id}",
      ...options,
    });

/**
 * Update Collaborator
 *
 * Update a collaborator's role.
 */
export const updateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPutData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).put<
      UpdateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPutResponses,
      UpdateCollaboratorApiV1CollaborationCollaboratorsCollaboratorIdPutErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/collaboration/collaborators/{collaborator_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Accept Invitation
 *
 * Accept a collaboration invitation using the token.
 */
export const acceptInvitationApiV1CollaborationInvitationsAcceptPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AcceptInvitationApiV1CollaborationInvitationsAcceptPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AcceptInvitationApiV1CollaborationInvitationsAcceptPostResponses,
    AcceptInvitationApiV1CollaborationInvitationsAcceptPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/collaboration/invitations/accept",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Accept Invitation By Id
 *
 * Accept a collaboration invitation by ID (for logged-in users).
 */
export const acceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      AcceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPostData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).post<
      AcceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPostResponses,
      AcceptInvitationByIdApiV1CollaborationInvitationsInvitationIdAcceptPostErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/collaboration/invitations/{invitation_id}/accept",
      ...options,
    });

/**
 * Decline Invitation
 *
 * Decline a collaboration invitation.
 */
export const declineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      DeclineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePostData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).post<
      DeclineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePostResponses,
      DeclineInvitationApiV1CollaborationInvitationsInvitationIdDeclinePostErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/collaboration/invitations/{invitation_id}/decline",
      ...options,
    });

/**
 * Leave Shared Inventory
 *
 * Leave a shared inventory.
 */
export const leaveSharedInventoryApiV1CollaborationSharedOwnerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    LeaveSharedInventoryApiV1CollaborationSharedOwnerIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    LeaveSharedInventoryApiV1CollaborationSharedOwnerIdDeleteResponses,
    LeaveSharedInventoryApiV1CollaborationSharedOwnerIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/collaboration/shared/{owner_id}",
    ...options,
  });
