// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostData,
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors,
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses,
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostData,
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors,
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses,
  ClassifyImageApiV1ImagesClassifyPostData,
  ClassifyImageApiV1ImagesClassifyPostErrors,
  ClassifyImageApiV1ImagesClassifyPostResponses,
  CreateCategoryApiV1CategoriesPostData,
  CreateCategoryApiV1CategoriesPostErrors,
  CreateCategoryApiV1CategoriesPostResponses,
  CreateCategoryFromPathApiV1CategoriesFromPathPostData,
  CreateCategoryFromPathApiV1CategoriesFromPathPostErrors,
  CreateCategoryFromPathApiV1CategoriesFromPathPostResponses,
  CreateCheckoutApiV1BillingCheckoutPostData,
  CreateCheckoutApiV1BillingCheckoutPostErrors,
  CreateCheckoutApiV1BillingCheckoutPostResponses,
  CreateItemApiV1ItemsPostData,
  CreateItemApiV1ItemsPostErrors,
  CreateItemApiV1ItemsPostResponses,
  CreateLocationApiV1LocationsPostData,
  CreateLocationApiV1LocationsPostErrors,
  CreateLocationApiV1LocationsPostResponses,
  CreatePackApiV1AdminPacksPostData,
  CreatePackApiV1AdminPacksPostErrors,
  CreatePackApiV1AdminPacksPostResponses,
  CreatePortalSessionApiV1BillingPortalPostData,
  CreatePortalSessionApiV1BillingPortalPostResponses,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteData,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
  DeleteImageApiV1ImagesImageIdDeleteData,
  DeleteImageApiV1ImagesImageIdDeleteErrors,
  DeleteImageApiV1ImagesImageIdDeleteResponses,
  DeleteItemApiV1ItemsItemIdDeleteData,
  DeleteItemApiV1ItemsItemIdDeleteErrors,
  DeleteItemApiV1ItemsItemIdDeleteResponses,
  DeleteLocationApiV1LocationsLocationIdDeleteData,
  DeleteLocationApiV1LocationsLocationIdDeleteErrors,
  DeleteLocationApiV1LocationsLocationIdDeleteResponses,
  DeletePackApiV1AdminPacksPackIdDeleteData,
  DeletePackApiV1AdminPacksPackIdDeleteErrors,
  DeletePackApiV1AdminPacksPackIdDeleteResponses,
  GetAllTagsApiV1ItemsTagsGetData,
  GetAllTagsApiV1ItemsTagsGetErrors,
  GetAllTagsApiV1ItemsTagsGetResponses,
  GetBalanceApiV1BillingBalanceGetData,
  GetBalanceApiV1BillingBalanceGetResponses,
  GetCategoryApiV1CategoriesCategoryIdGetData,
  GetCategoryApiV1CategoriesCategoryIdGetErrors,
  GetCategoryApiV1CategoriesCategoryIdGetResponses,
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetData,
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors,
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses,
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetData,
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors,
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses,
  GetCategoryTreeApiV1CategoriesTreeGetData,
  GetCategoryTreeApiV1CategoriesTreeGetResponses,
  GetCurrentUserInfoApiV1AuthMeGetData,
  GetCurrentUserInfoApiV1AuthMeGetResponses,
  GetDashboardStatsApiV1ItemsStatsDashboardGetData,
  GetDashboardStatsApiV1ItemsStatsDashboardGetErrors,
  GetDashboardStatsApiV1ItemsStatsDashboardGetResponses,
  GetImageApiV1ImagesImageIdGetData,
  GetImageApiV1ImagesImageIdGetErrors,
  GetImageApiV1ImagesImageIdGetResponses,
  GetImageFileApiV1ImagesImageIdFileGetData,
  GetImageFileApiV1ImagesImageIdFileGetErrors,
  GetImageFileApiV1ImagesImageIdFileGetResponses,
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetData,
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors,
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses,
  GetItemApiV1ItemsItemIdGetData,
  GetItemApiV1ItemsItemIdGetErrors,
  GetItemApiV1ItemsItemIdGetResponses,
  GetItemFacetsApiV1ItemsFacetsGetData,
  GetItemFacetsApiV1ItemsFacetsGetErrors,
  GetItemFacetsApiV1ItemsFacetsGetResponses,
  GetLocationApiV1LocationsLocationIdGetData,
  GetLocationApiV1LocationsLocationIdGetErrors,
  GetLocationApiV1LocationsLocationIdGetResponses,
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetData,
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors,
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses,
  GetLocationTreeApiV1LocationsTreeGetData,
  GetLocationTreeApiV1LocationsTreeGetResponses,
  GetPackApiV1AdminPacksPackIdGetData,
  GetPackApiV1AdminPacksPackIdGetErrors,
  GetPackApiV1AdminPacksPackIdGetResponses,
  GetStatsApiV1AdminStatsGetData,
  GetStatsApiV1AdminStatsGetResponses,
  GetUserApiV1AdminUsersUserIdGetData,
  GetUserApiV1AdminUsersUserIdGetErrors,
  GetUserApiV1AdminUsersUserIdGetResponses,
  GoogleAuthApiV1AuthGoogleGetData,
  GoogleAuthApiV1AuthGoogleGetErrors,
  GoogleAuthApiV1AuthGoogleGetResponses,
  GoogleCallbackApiV1AuthCallbackGoogleGetData,
  GoogleCallbackApiV1AuthCallbackGoogleGetErrors,
  GoogleCallbackApiV1AuthCallbackGoogleGetResponses,
  HandleWebhookApiV1BillingWebhookPostData,
  HandleWebhookApiV1BillingWebhookPostErrors,
  HandleWebhookApiV1BillingWebhookPostResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  ListCategoriesApiV1CategoriesGetData,
  ListCategoriesApiV1CategoriesGetResponses,
  ListClassifiedImagesApiV1ImagesClassifiedGetData,
  ListClassifiedImagesApiV1ImagesClassifiedGetErrors,
  ListClassifiedImagesApiV1ImagesClassifiedGetResponses,
  ListItemsApiV1ItemsGetData,
  ListItemsApiV1ItemsGetErrors,
  ListItemsApiV1ItemsGetResponses,
  ListLocationsApiV1LocationsGetData,
  ListLocationsApiV1LocationsGetResponses,
  ListLowStockItemsApiV1ItemsLowStockGetData,
  ListLowStockItemsApiV1ItemsLowStockGetResponses,
  ListPacksApiV1AdminPacksGetData,
  ListPacksApiV1AdminPacksGetResponses,
  ListPacksApiV1BillingPacksGetData,
  ListPacksApiV1BillingPacksGetResponses,
  ListTransactionsApiV1BillingTransactionsGetData,
  ListTransactionsApiV1BillingTransactionsGetErrors,
  ListTransactionsApiV1BillingTransactionsGetResponses,
  ListUsersApiV1AdminUsersGetData,
  ListUsersApiV1AdminUsersGetErrors,
  ListUsersApiV1AdminUsersGetResponses,
  MoveCategoryApiV1CategoriesCategoryIdMovePatchData,
  MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors,
  MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses,
  MoveLocationApiV1LocationsLocationIdMovePatchData,
  MoveLocationApiV1LocationsLocationIdMovePatchErrors,
  MoveLocationApiV1LocationsLocationIdMovePatchResponses,
  RefreshTokenApiV1AuthRefreshPostData,
  RefreshTokenApiV1AuthRefreshPostResponses,
  RequestRefundApiV1BillingRefundPostData,
  RequestRefundApiV1BillingRefundPostErrors,
  RequestRefundApiV1BillingRefundPostResponses,
  SearchItemsApiV1ItemsSearchGetData,
  SearchItemsApiV1ItemsSearchGetErrors,
  SearchItemsApiV1ItemsSearchGetResponses,
  UpdateCategoryApiV1CategoriesCategoryIdPutData,
  UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
  UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
  UpdateItemApiV1ItemsItemIdPutData,
  UpdateItemApiV1ItemsItemIdPutErrors,
  UpdateItemApiV1ItemsItemIdPutResponses,
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchData,
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors,
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses,
  UpdateLocationApiV1LocationsLocationIdPutData,
  UpdateLocationApiV1LocationsLocationIdPutErrors,
  UpdateLocationApiV1LocationsLocationIdPutResponses,
  UpdatePackApiV1AdminPacksPackIdPutData,
  UpdatePackApiV1AdminPacksPackIdPutErrors,
  UpdatePackApiV1AdminPacksPackIdPutResponses,
  UpdateUserApiV1AdminUsersUserIdPutData,
  UpdateUserApiV1AdminUsersUserIdPutErrors,
  UpdateUserApiV1AdminUsersUserIdPutResponses,
  UploadImageApiV1ImagesUploadPostData,
  UploadImageApiV1ImagesUploadPostErrors,
  UploadImageApiV1ImagesUploadPostResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * List Packs
 *
 * List all credit packs (including inactive) for admin.
 */
export const listPacksApiV1AdminPacksGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListPacksApiV1AdminPacksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPacksApiV1AdminPacksGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs",
    ...options,
  });

/**
 * Create Pack
 *
 * Create a new credit pack.
 */
export const createPackApiV1AdminPacksPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreatePackApiV1AdminPacksPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreatePackApiV1AdminPacksPostResponses,
    CreatePackApiV1AdminPacksPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Pack
 *
 * Delete a credit pack (soft delete by setting inactive).
 */
export const deletePackApiV1AdminPacksPackIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePackApiV1AdminPacksPackIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeletePackApiV1AdminPacksPackIdDeleteResponses,
    DeletePackApiV1AdminPacksPackIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs/{pack_id}",
    ...options,
  });

/**
 * Get Pack
 *
 * Get a specific credit pack.
 */
export const getPackApiV1AdminPacksPackIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPackApiV1AdminPacksPackIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPackApiV1AdminPacksPackIdGetResponses,
    GetPackApiV1AdminPacksPackIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs/{pack_id}",
    ...options,
  });

/**
 * Update Pack
 *
 * Update a credit pack.
 */
export const updatePackApiV1AdminPacksPackIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePackApiV1AdminPacksPackIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdatePackApiV1AdminPacksPackIdPutResponses,
    UpdatePackApiV1AdminPacksPackIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/packs/{pack_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Users
 *
 * List all users with pagination.
 */
export const listUsersApiV1AdminUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUsersApiV1AdminUsersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersApiV1AdminUsersGetResponses,
    ListUsersApiV1AdminUsersGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users",
    ...options,
  });

/**
 * Get User
 *
 * Get a specific user.
 */
export const getUserApiV1AdminUsersUserIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserApiV1AdminUsersUserIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUserApiV1AdminUsersUserIdGetResponses,
    GetUserApiV1AdminUsersUserIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users/{user_id}",
    ...options,
  });

/**
 * Update User
 *
 * Update a user (admin status).
 */
export const updateUserApiV1AdminUsersUserIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserApiV1AdminUsersUserIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUserApiV1AdminUsersUserIdPutResponses,
    UpdateUserApiV1AdminUsersUserIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Adjust User Credits
 *
 * Grant or remove credits from a user.
 */
export const adjustUserCreditsApiV1AdminUsersUserIdCreditsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses,
    AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/users/{user_id}/credits",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Stats
 *
 * Get admin dashboard statistics.
 */
export const getStatsApiV1AdminStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetStatsApiV1AdminStatsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetStatsApiV1AdminStatsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/stats",
    ...options,
  });

/**
 * Google Auth
 *
 * Get Google OAuth authorization URL.
 *
 * The client should redirect to this URL to initiate OAuth flow.
 */
export const googleAuthApiV1AuthGoogleGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GoogleAuthApiV1AuthGoogleGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GoogleAuthApiV1AuthGoogleGetResponses,
    GoogleAuthApiV1AuthGoogleGetErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/google", ...options });

/**
 * Google Callback
 *
 * Handle Google OAuth callback.
 *
 * Exchange the authorization code for tokens and create/get user.
 */
export const googleCallbackApiV1AuthCallbackGoogleGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GoogleCallbackApiV1AuthCallbackGoogleGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GoogleCallbackApiV1AuthCallbackGoogleGetResponses,
    GoogleCallbackApiV1AuthCallbackGoogleGetErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/callback/google", ...options });

/**
 * Get Current User Info
 *
 * Get the current authenticated user's information.
 */
export const getCurrentUserInfoApiV1AuthMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCurrentUserInfoApiV1AuthMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCurrentUserInfoApiV1AuthMeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/me",
    ...options,
  });

/**
 * Refresh Token
 *
 * Refresh the access token.
 */
export const refreshTokenApiV1AuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshTokenApiV1AuthRefreshPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    RefreshTokenApiV1AuthRefreshPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/refresh",
    ...options,
  });

/**
 * Get Balance
 *
 * Get current credit balance for the authenticated user.
 */
export const getBalanceApiV1BillingBalanceGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetBalanceApiV1BillingBalanceGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetBalanceApiV1BillingBalanceGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/balance",
    ...options,
  });

/**
 * List Packs
 *
 * List all available credit packs.
 */
export const listPacksApiV1BillingPacksGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListPacksApiV1BillingPacksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPacksApiV1BillingPacksGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/billing/packs", ...options });

/**
 * Create Checkout
 *
 * Create a Stripe checkout session for purchasing credits.
 */
export const createCheckoutApiV1BillingCheckoutPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCheckoutApiV1BillingCheckoutPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCheckoutApiV1BillingCheckoutPostResponses,
    CreateCheckoutApiV1BillingCheckoutPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/checkout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Transactions
 *
 * Get transaction history for the authenticated user.
 */
export const listTransactionsApiV1BillingTransactionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListTransactionsApiV1BillingTransactionsGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListTransactionsApiV1BillingTransactionsGetResponses,
    ListTransactionsApiV1BillingTransactionsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/transactions",
    ...options,
  });

/**
 * Create Portal Session
 *
 * Create a Stripe customer portal session.
 */
export const createPortalSessionApiV1BillingPortalPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CreatePortalSessionApiV1BillingPortalPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    CreatePortalSessionApiV1BillingPortalPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/portal",
    ...options,
  });

/**
 * Request Refund
 *
 * Request a refund for an unused credit purchase.
 */
export const requestRefundApiV1BillingRefundPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RequestRefundApiV1BillingRefundPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RequestRefundApiV1BillingRefundPostResponses,
    RequestRefundApiV1BillingRefundPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/billing/refund",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Handle Webhook
 *
 * Handle Stripe webhook events.
 */
export const handleWebhookApiV1BillingWebhookPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<HandleWebhookApiV1BillingWebhookPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    HandleWebhookApiV1BillingWebhookPostResponses,
    HandleWebhookApiV1BillingWebhookPostErrors,
    ThrowOnError
  >({ url: "/api/v1/billing/webhook", ...options });

/**
 * List Items
 *
 * List items with filtering and pagination.
 *
 * When filtering by category or location, child categories/locations are included by default.
 * Set include_subcategories=false or include_sublocations=false to filter by exact match only.
 *
 * Filter by tags using ?tags=tag1&tags=tag2 (items must have ALL specified tags).
 * Filter by attributes using ?attr=key1:value1&attr=key2:value2.
 */
export const listItemsApiV1ItemsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListItemsApiV1ItemsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListItemsApiV1ItemsGetResponses,
    ListItemsApiV1ItemsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items",
    ...options,
  });

/**
 * Create Item
 *
 * Create a new item.
 */
export const createItemApiV1ItemsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemApiV1ItemsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateItemApiV1ItemsPostResponses,
    CreateItemApiV1ItemsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Dashboard Stats
 *
 * Get dashboard statistics including time series data.
 */
export const getDashboardStatsApiV1ItemsStatsDashboardGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetDashboardStatsApiV1ItemsStatsDashboardGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    GetDashboardStatsApiV1ItemsStatsDashboardGetResponses,
    GetDashboardStatsApiV1ItemsStatsDashboardGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/stats/dashboard",
    ...options,
  });

/**
 * Search Items
 *
 * Search items by name, description, or tags.
 */
export const searchItemsApiV1ItemsSearchGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SearchItemsApiV1ItemsSearchGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SearchItemsApiV1ItemsSearchGetResponses,
    SearchItemsApiV1ItemsSearchGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/search",
    ...options,
  });

/**
 * List Low Stock Items
 *
 * List items that are below their minimum quantity threshold.
 */
export const listLowStockItemsApiV1ItemsLowStockGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListLowStockItemsApiV1ItemsLowStockGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListLowStockItemsApiV1ItemsLowStockGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/low-stock",
    ...options,
  });

/**
 * Get Item Facets
 *
 * Get available facets (attribute values with counts) for filtering.
 *
 * Facets are based on the category's attribute template if a category is specified,
 * or all unique attribute keys found in matching items.
 */
export const getItemFacetsApiV1ItemsFacetsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetItemFacetsApiV1ItemsFacetsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetItemFacetsApiV1ItemsFacetsGetResponses,
    GetItemFacetsApiV1ItemsFacetsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/facets",
    ...options,
  });

/**
 * Get All Tags
 *
 * Get all unique tags with their counts.
 */
export const getAllTagsApiV1ItemsTagsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllTagsApiV1ItemsTagsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetAllTagsApiV1ItemsTagsGetResponses,
    GetAllTagsApiV1ItemsTagsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/tags",
    ...options,
  });

/**
 * Delete Item
 *
 * Delete an item.
 */
export const deleteItemApiV1ItemsItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemApiV1ItemsItemIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteItemApiV1ItemsItemIdDeleteResponses,
    DeleteItemApiV1ItemsItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}",
    ...options,
  });

/**
 * Get Item
 *
 * Get an item by ID.
 */
export const getItemApiV1ItemsItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemApiV1ItemsItemIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetItemApiV1ItemsItemIdGetResponses,
    GetItemApiV1ItemsItemIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}",
    ...options,
  });

/**
 * Update Item
 *
 * Update an item.
 */
export const updateItemApiV1ItemsItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateItemApiV1ItemsItemIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateItemApiV1ItemsItemIdPutResponses,
    UpdateItemApiV1ItemsItemIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Item Quantity
 *
 * Quick update for item quantity.
 */
export const updateItemQuantityApiV1ItemsItemIdQuantityPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateItemQuantityApiV1ItemsItemIdQuantityPatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses,
    UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{item_id}/quantity",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Categories
 *
 * List all categories for the current user, ordered by hierarchy path.
 */
export const listCategoriesApiV1CategoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCategoriesApiV1CategoriesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListCategoriesApiV1CategoriesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories",
    ...options,
  });

/**
 * Create Category
 *
 * Create a new category.
 */
export const createCategoryApiV1CategoriesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCategoryApiV1CategoriesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCategoryApiV1CategoriesPostResponses,
    CreateCategoryApiV1CategoriesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Category Tree
 *
 * Get categories as a nested tree structure with item counts.
 */
export const getCategoryTreeApiV1CategoriesTreeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCategoryTreeApiV1CategoriesTreeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCategoryTreeApiV1CategoriesTreeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/tree",
    ...options,
  });

/**
 * Create Category From Path
 *
 * Create categories from an AI-suggested path.
 *
 * Parses a path like 'Hardware > Fasteners > Screws' and creates any
 * missing categories in the hierarchy. Returns the leaf category.
 */
export const createCategoryFromPathApiV1CategoriesFromPathPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateCategoryFromPathApiV1CategoriesFromPathPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateCategoryFromPathApiV1CategoriesFromPathPostResponses,
    CreateCategoryFromPathApiV1CategoriesFromPathPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/from-path",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Category
 *
 * Delete a category. Child categories will become root-level categories.
 */
export const deleteCategoryApiV1CategoriesCategoryIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCategoryApiV1CategoriesCategoryIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
    DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}",
    ...options,
  });

/**
 * Get Category
 *
 * Get a category by ID.
 */
export const getCategoryApiV1CategoriesCategoryIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCategoryApiV1CategoriesCategoryIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCategoryApiV1CategoriesCategoryIdGetResponses,
    GetCategoryApiV1CategoriesCategoryIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}",
    ...options,
  });

/**
 * Update Category
 *
 * Update a category.
 */
export const updateCategoryApiV1CategoriesCategoryIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCategoryApiV1CategoriesCategoryIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
    UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Category Template
 *
 * Get merged attribute template for a category.
 *
 * Returns fields from this category and all ancestors, with child fields
 * overriding parent fields of the same name.
 */
export const getCategoryTemplateApiV1CategoriesCategoryIdTemplateGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses,
    GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}/template",
    ...options,
  });

/**
 * Get Category Descendants
 *
 * Get all descendant categories of a category.
 */
export const getCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses,
    GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}/descendants",
    ...options,
  });

/**
 * Move Category
 *
 * Move a category to a new parent (or to root level if new_parent_id is null).
 */
export const moveCategoryApiV1CategoriesCategoryIdMovePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    MoveCategoryApiV1CategoriesCategoryIdMovePatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses,
    MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/categories/{category_id}/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Locations
 *
 * List all locations for the current user, ordered by hierarchy path.
 */
export const listLocationsApiV1LocationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListLocationsApiV1LocationsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListLocationsApiV1LocationsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations",
    ...options,
  });

/**
 * Create Location
 *
 * Create a new location.
 */
export const createLocationApiV1LocationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateLocationApiV1LocationsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateLocationApiV1LocationsPostResponses,
    CreateLocationApiV1LocationsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Location Tree
 *
 * Get locations as a nested tree structure with item counts.
 */
export const getLocationTreeApiV1LocationsTreeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetLocationTreeApiV1LocationsTreeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetLocationTreeApiV1LocationsTreeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/tree",
    ...options,
  });

/**
 * Delete Location
 *
 * Delete a location. Child locations will become root-level locations.
 */
export const deleteLocationApiV1LocationsLocationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteLocationApiV1LocationsLocationIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteLocationApiV1LocationsLocationIdDeleteResponses,
    DeleteLocationApiV1LocationsLocationIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}",
    ...options,
  });

/**
 * Get Location
 *
 * Get a location by ID.
 */
export const getLocationApiV1LocationsLocationIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLocationApiV1LocationsLocationIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLocationApiV1LocationsLocationIdGetResponses,
    GetLocationApiV1LocationsLocationIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}",
    ...options,
  });

/**
 * Update Location
 *
 * Update a location.
 */
export const updateLocationApiV1LocationsLocationIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateLocationApiV1LocationsLocationIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateLocationApiV1LocationsLocationIdPutResponses,
    UpdateLocationApiV1LocationsLocationIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Location Descendants
 *
 * Get all descendant locations of a location.
 */
export const getLocationDescendantsApiV1LocationsLocationIdDescendantsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses,
    GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}/descendants",
    ...options,
  });

/**
 * Move Location
 *
 * Move a location to a new parent (or to root level if new_parent_id is null).
 */
export const moveLocationApiV1LocationsLocationIdMovePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    MoveLocationApiV1LocationsLocationIdMovePatchData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    MoveLocationApiV1LocationsLocationIdMovePatchResponses,
    MoveLocationApiV1LocationsLocationIdMovePatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/locations/{location_id}/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload Image
 *
 * Upload an image file.
 *
 * If the same image content was previously uploaded by this user,
 * returns the existing image record instead of creating a duplicate.
 */
export const uploadImageApiV1ImagesUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UploadImageApiV1ImagesUploadPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadImageApiV1ImagesUploadPostResponses,
    UploadImageApiV1ImagesUploadPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Classify Image
 *
 * Classify an uploaded image using AI.
 */
export const classifyImageApiV1ImagesClassifyPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ClassifyImageApiV1ImagesClassifyPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ClassifyImageApiV1ImagesClassifyPostResponses,
    ClassifyImageApiV1ImagesClassifyPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/classify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Classified Images
 *
 * List all images that have been classified by AI.
 */
export const listClassifiedImagesApiV1ImagesClassifiedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListClassifiedImagesApiV1ImagesClassifiedGetData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListClassifiedImagesApiV1ImagesClassifiedGetResponses,
    ListClassifiedImagesApiV1ImagesClassifiedGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/classified",
    ...options,
  });

/**
 * Delete Image
 *
 * Delete an image.
 */
export const deleteImageApiV1ImagesImageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteImageApiV1ImagesImageIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteImageApiV1ImagesImageIdDeleteResponses,
    DeleteImageApiV1ImagesImageIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}",
    ...options,
  });

/**
 * Get Image
 *
 * Get image metadata.
 */
export const getImageApiV1ImagesImageIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetImageApiV1ImagesImageIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetImageApiV1ImagesImageIdGetResponses,
    GetImageApiV1ImagesImageIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}",
    ...options,
  });

/**
 * Get Image Signed Url
 *
 * Get a signed URL for accessing an image file.
 *
 * This generates a short-lived token that can be used in browser <img> tags
 * where Authorization headers cannot be sent.
 */
export const getImageSignedUrlApiV1ImagesImageIdSignedUrlGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses,
    GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}/signed-url",
    ...options,
  });

/**
 * Get Image File
 *
 * Get the actual image file.
 *
 * Requires a valid signed token query parameter for authentication.
 * Use GET /{image_id}/signed-url to obtain a token.
 */
export const getImageFileApiV1ImagesImageIdFileGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetImageFileApiV1ImagesImageIdFileGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetImageFileApiV1ImagesImageIdFileGetResponses,
    GetImageFileApiV1ImagesImageIdFileGetErrors,
    ThrowOnError
  >({ url: "/api/v1/images/{image_id}/file", ...options });

/**
 * Attach Image To Item
 *
 * Attach an image to an item.
 */
export const attachImageToItemApiV1ImagesImageIdAttachItemIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AttachImageToItemApiV1ImagesImageIdAttachItemIdPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses,
    AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/images/{image_id}/attach/{item_id}",
    ...options,
  });
