// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * AdminStatsResponse
 *
 * Admin dashboard statistics.
 */
export type AdminStatsResponse = {
  /**
   * Total Users
   */
  total_users: number;
  /**
   * Total Items
   */
  total_items: number;
  /**
   * Total Revenue Cents
   */
  total_revenue_cents: number;
  /**
   * Active Credit Packs
   */
  active_credit_packs: number;
  /**
   * Total Credits Purchased
   */
  total_credits_purchased: number;
  /**
   * Total Credits Used
   */
  total_credits_used: number;
};

/**
 * AttributeField
 *
 * Schema for a single attribute field in a category template.
 */
export type AttributeField = {
  /**
   * Name
   *
   * Field identifier (snake_case)
   */
  name: string;
  /**
   * Label
   *
   * Display label
   */
  label: string;
  /**
   * Type
   *
   * Field input type
   */
  type: "text" | "number" | "select" | "boolean";
  /**
   * Options
   *
   * Options for select type fields
   */
  options?: Array<string> | null;
  /**
   * Required
   *
   * Whether field is required
   */
  required?: boolean;
  /**
   * Default
   *
   * Default value
   */
  default?: string | number | number | boolean | null;
  /**
   * Unit
   *
   * Unit suffix (e.g., 'mm', 'ohms')
   */
  unit?: string | null;
};

/**
 * AttributeTemplate
 *
 * Schema for category attribute template.
 */
export type AttributeTemplate = {
  /**
   * Fields
   */
  fields?: Array<AttributeField>;
};

/**
 * AuthResponse
 *
 * Schema for authentication response with user info.
 */
export type AuthResponse = {
  token: TokenResponse;
  user: UserResponse;
};

/**
 * Body_upload_image_api_v1_images_upload_post
 */
export type BodyUploadImageApiV1ImagesUploadPost = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * CategoryCreate
 *
 * Schema for creating a category.
 */
export type CategoryCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Parent Id
   *
   * Parent category ID for hierarchy
   */
  parent_id?: string | null;
  /**
   * Template for item attributes in this category
   */
  attribute_template?: AttributeTemplate | null;
};

/**
 * CategoryCreateFromPath
 *
 * Schema for creating categories from an AI-suggested path.
 */
export type CategoryCreateFromPath = {
  /**
   * Path
   *
   * Category path like 'Hardware > Fasteners > Screws'
   */
  path: string;
};

/**
 * CategoryDistribution
 *
 * Distribution of items by category.
 */
export type CategoryDistribution = {
  /**
   * Name
   */
  name: string;
  /**
   * Count
   */
  count: number;
};

/**
 * CategoryMoveRequest
 *
 * Schema for moving a category to a new parent.
 */
export type CategoryMoveRequest = {
  /**
   * New Parent Id
   *
   * New parent category ID, or null for root level
   */
  new_parent_id?: string | null;
};

/**
 * CategoryResponse
 *
 * Schema for category responses.
 */
export type CategoryResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Path
   */
  path?: string;
  /**
   * Attribute Template
   */
  attribute_template?: {
    [key: string]: unknown;
  };
  /**
   * Created At
   */
  created_at: string;
};

/**
 * CategoryTreeNode
 *
 * Schema for nested category tree representation.
 */
export type CategoryTreeNode = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Path
   */
  path: string;
  /**
   * Attribute Template
   */
  attribute_template?: {
    [key: string]: unknown;
  };
  /**
   * Item Count
   */
  item_count?: number;
  /**
   * Total Value
   */
  total_value?: number;
  /**
   * Children
   */
  children?: Array<CategoryTreeNode>;
};

/**
 * CategoryUpdate
 *
 * Schema for updating a category.
 */
export type CategoryUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Parent Id
   *
   * Parent category ID (set to null to make root)
   */
  parent_id?: string | null;
  /**
   * Template for item attributes
   */
  attribute_template?: AttributeTemplate | null;
};

/**
 * CheckoutRequest
 *
 * Request schema for creating checkout session.
 */
export type CheckoutRequest = {
  /**
   * Pack Id
   *
   * Credit pack ID to purchase
   */
  pack_id: string;
};

/**
 * CheckoutResponse
 *
 * Response schema for checkout session.
 */
export type CheckoutResponse = {
  /**
   * Checkout Url
   *
   * Stripe checkout URL
   */
  checkout_url: string;
};

/**
 * ClassificationRequest
 *
 * Schema for image classification request.
 */
export type ClassificationRequest = {
  /**
   * Image Id
   */
  image_id: string;
};

/**
 * ClassificationResponse
 *
 * Schema for classification response.
 */
export type ClassificationResponse = {
  /**
   * Success
   */
  success: boolean;
  classification?: ClassificationResult | null;
  /**
   * Error
   */
  error?: string | null;
  /**
   * Create Item Prefill
   */
  create_item_prefill?: {
    [key: string]: unknown;
  } | null;
};

/**
 * ClassificationResult
 *
 * Schema for AI classification result.
 */
export type ClassificationResult = {
  /**
   * Identified Name
   */
  identified_name: string;
  /**
   * Confidence
   */
  confidence: number;
  /**
   * Category Path
   */
  category_path: string;
  /**
   * Description
   */
  description: string;
  /**
   * Specifications
   */
  specifications: {
    [key: string]: unknown;
  };
  /**
   * Alternative Suggestions
   */
  alternative_suggestions?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Quantity Estimate
   */
  quantity_estimate?: string | null;
};

/**
 * CreditAdjustmentRequest
 *
 * Schema for admin credit adjustment.
 */
export type CreditAdjustmentRequest = {
  /**
   * Amount
   *
   * Purchased credits to add (positive) or remove (negative)
   */
  amount?: number;
  /**
   * Free Credits Amount
   *
   * Free credits to add (positive) or remove (negative)
   */
  free_credits_amount?: number;
  /**
   * Reason
   *
   * Reason for adjustment
   */
  reason: string;
};

/**
 * CreditAdjustmentResponse
 *
 * Response for credit adjustment.
 */
export type CreditAdjustmentResponse = {
  /**
   * User Id
   */
  user_id: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Free Credits Amount
   */
  free_credits_amount: number;
  /**
   * New Balance
   */
  new_balance: number;
  /**
   * New Free Credits
   */
  new_free_credits: number;
  /**
   * Reason
   */
  reason: string;
};

/**
 * CreditBalanceResponse
 *
 * Response schema for credit balance.
 */
export type CreditBalanceResponse = {
  /**
   * Purchased Credits
   *
   * Purchased credits (never expire)
   */
  purchased_credits: number;
  /**
   * Free Credits
   *
   * Free credits remaining this month
   */
  free_credits: number;
  /**
   * Total Credits
   *
   * Total available credits
   */
  total_credits: number;
  /**
   * Next Free Reset At
   *
   * When free credits will reset
   */
  next_free_reset_at?: string | null;
};

/**
 * CreditPackAdminResponse
 *
 * Admin response schema for credit pack (includes inactive packs).
 */
export type CreditPackAdminResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Credits
   */
  credits: number;
  /**
   * Price Cents
   */
  price_cents: number;
  /**
   * Stripe Price Id
   */
  stripe_price_id: string;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Sort Order
   */
  sort_order: number;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * CreditPackCreate
 *
 * Schema for creating a credit pack.
 */
export type CreditPackCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Credits
   */
  credits: number;
  /**
   * Price Cents
   */
  price_cents: number;
  /**
   * Stripe Price Id
   */
  stripe_price_id: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Sort Order
   */
  sort_order?: number;
};

/**
 * CreditPackResponse
 *
 * Response schema for credit pack.
 */
export type CreditPackResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Credits
   */
  credits: number;
  /**
   * Price Cents
   */
  price_cents: number;
  /**
   * Stripe Price Id
   */
  stripe_price_id: string;
  /**
   * Is Best Value
   */
  is_best_value?: boolean;
};

/**
 * CreditPackUpdate
 *
 * Schema for updating a credit pack.
 */
export type CreditPackUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Credits
   */
  credits?: number | null;
  /**
   * Price Cents
   */
  price_cents?: number | null;
  /**
   * Stripe Price Id
   */
  stripe_price_id?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Sort Order
   */
  sort_order?: number | null;
};

/**
 * DashboardStatsResponse
 *
 * Dashboard statistics response.
 */
export type DashboardStatsResponse = {
  /**
   * Items Over Time
   */
  items_over_time: Array<TimeSeriesDataPoint>;
  /**
   * Items By Category
   */
  items_by_category: Array<CategoryDistribution>;
  /**
   * Items By Location
   */
  items_by_location: Array<LocationDistribution>;
  /**
   * Total Items
   */
  total_items: number;
  /**
   * Total Quantity
   */
  total_quantity: number;
  /**
   * Categories Used
   */
  categories_used: number;
  /**
   * Locations Used
   */
  locations_used: number;
};

/**
 * Facet
 *
 * A facet (attribute) with its available values.
 */
export type Facet = {
  /**
   * Name
   */
  name: string;
  /**
   * Label
   */
  label: string;
  /**
   * Values
   */
  values: Array<FacetValue>;
};

/**
 * FacetValue
 *
 * A single value in a facet with count.
 */
export type FacetValue = {
  /**
   * Value
   */
  value: string;
  /**
   * Count
   */
  count: number;
};

/**
 * FacetedSearchResponse
 *
 * Response containing available facets for filtering.
 */
export type FacetedSearchResponse = {
  /**
   * Facets
   */
  facets: Array<Facet>;
  /**
   * Total Items
   */
  total_items: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImageResponse
 *
 * Schema for image response.
 */
export type ImageResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Storage Path
   */
  storage_path: string;
  /**
   * Original Filename
   */
  original_filename: string | null;
  /**
   * Mime Type
   */
  mime_type: string | null;
  /**
   * Size Bytes
   */
  size_bytes: number | null;
  /**
   * Content Hash
   */
  content_hash: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Item Id
   */
  item_id: string | null;
  /**
   * Is Primary
   */
  is_primary: boolean;
  /**
   * Ai Processed
   */
  ai_processed: boolean;
  /**
   * Ai Result
   */
  ai_result: {
    [key: string]: unknown;
  } | null;
};

/**
 * ImageSignedUrlResponse
 *
 * Schema for signed URL response.
 */
export type ImageSignedUrlResponse = {
  /**
   * Url
   */
  url: string;
};

/**
 * ImageUploadResponse
 *
 * Schema for image upload response.
 */
export type ImageUploadResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Storage Path
   */
  storage_path: string;
  /**
   * Original Filename
   */
  original_filename: string | null;
  /**
   * Mime Type
   */
  mime_type: string | null;
  /**
   * Size Bytes
   */
  size_bytes: number | null;
  /**
   * Content Hash
   */
  content_hash: string | null;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ItemCreate
 *
 * Schema for creating an item.
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Category Id
   */
  category_id?: string | null;
  /**
   * Location Id
   */
  location_id?: string | null;
  /**
   * Quantity
   */
  quantity?: number;
  /**
   * Quantity Unit
   */
  quantity_unit?: string;
  /**
   * Min Quantity
   */
  min_quantity?: number | null;
  /**
   * Price
   */
  price?: number | string | null;
  /**
   * Attributes
   */
  attributes?: {
    [key: string]: unknown;
  };
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Image Ids
   */
  image_ids?: Array<string> | null;
};

/**
 * ItemDetailResponse
 *
 * Schema for detailed item response with related entities.
 */
export type ItemDetailResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Category Id
   */
  category_id?: string | null;
  /**
   * Location Id
   */
  location_id?: string | null;
  /**
   * Quantity
   */
  quantity?: number;
  /**
   * Quantity Unit
   */
  quantity_unit?: string;
  /**
   * Min Quantity
   */
  min_quantity?: number | null;
  /**
   * Price
   */
  price?: string | null;
  /**
   * Attributes
   */
  attributes?: {
    [key: string]: unknown;
  };
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Id
   */
  id: string;
  /**
   * Ai Classification
   */
  ai_classification: {
    [key: string]: unknown;
  };
  /**
   * Is Low Stock
   */
  is_low_stock: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  category?: CategoryResponse | null;
  location?: LocationResponse | null;
  /**
   * Primary Image Url
   */
  primary_image_url?: string | null;
};

/**
 * ItemListResponse
 *
 * Schema for item list item.
 */
export type ItemListResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string | null;
  /**
   * Quantity
   */
  quantity: number;
  /**
   * Quantity Unit
   */
  quantity_unit: string;
  /**
   * Price
   */
  price?: string | null;
  /**
   * Is Low Stock
   */
  is_low_stock: boolean;
  /**
   * Tags
   */
  tags?: Array<string>;
  category?: CategoryResponse | null;
  location?: LocationResponse | null;
  /**
   * Primary Image Url
   */
  primary_image_url?: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * ItemUpdate
 *
 * Schema for updating an item.
 */
export type ItemUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Category Id
   */
  category_id?: string | null;
  /**
   * Location Id
   */
  location_id?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Quantity Unit
   */
  quantity_unit?: string | null;
  /**
   * Min Quantity
   */
  min_quantity?: number | null;
  /**
   * Price
   */
  price?: number | string | null;
  /**
   * Attributes
   */
  attributes?: {
    [key: string]: unknown;
  } | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
};

/**
 * LocationCreate
 *
 * Schema for creating a location.
 */
export type LocationCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Location Type
   */
  location_type?: string | null;
  /**
   * Parent Id
   *
   * Parent location ID for hierarchy
   */
  parent_id?: string | null;
};

/**
 * LocationDistribution
 *
 * Distribution of items by location.
 */
export type LocationDistribution = {
  /**
   * Name
   */
  name: string;
  /**
   * Count
   */
  count: number;
};

/**
 * LocationMoveRequest
 *
 * Schema for moving a location to a new parent.
 */
export type LocationMoveRequest = {
  /**
   * New Parent Id
   *
   * New parent location ID, or null for root level
   */
  new_parent_id?: string | null;
};

/**
 * LocationResponse
 *
 * Schema for location responses.
 */
export type LocationResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Location Type
   */
  location_type?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Path
   */
  path?: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * LocationTreeNode
 *
 * Schema for nested location tree representation.
 */
export type LocationTreeNode = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Location Type
   */
  location_type?: string | null;
  /**
   * Path
   */
  path: string;
  /**
   * Item Count
   */
  item_count?: number;
  /**
   * Total Value
   */
  total_value?: number;
  /**
   * Children
   */
  children?: Array<LocationTreeNode>;
};

/**
 * LocationUpdate
 *
 * Schema for updating a location.
 */
export type LocationUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Location Type
   */
  location_type?: string | null;
  /**
   * Parent Id
   *
   * Parent location ID (set to null to make root)
   */
  parent_id?: string | null;
};

/**
 * MergedAttributeTemplate
 *
 * Schema for merged attribute template from category hierarchy.
 */
export type MergedAttributeTemplate = {
  /**
   * Fields
   */
  fields?: Array<AttributeField>;
  /**
   * Inherited From
   *
   * Category IDs from which fields were inherited
   */
  inherited_from?: Array<string>;
};

/**
 * PaginatedImagesResponse
 *
 * Schema for paginated images response.
 */
export type PaginatedImagesResponse = {
  /**
   * Items
   */
  items: Array<ImageResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Limit
   */
  limit: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * PaginatedResponse[ItemListResponse]
 */
export type PaginatedResponseItemListResponse = {
  /**
   * Items
   */
  items: Array<ItemListResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Limit
   */
  limit: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * PaginatedTransactionResponse
 *
 * Paginated response for transactions.
 */
export type PaginatedTransactionResponse = {
  /**
   * Items
   */
  items: Array<TransactionResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Limit
   */
  limit: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * PaginatedUsersResponse
 *
 * Paginated response for users.
 */
export type PaginatedUsersResponse = {
  /**
   * Items
   */
  items: Array<UserAdminResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Limit
   */
  limit: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * PortalResponse
 *
 * Response schema for customer portal session.
 */
export type PortalResponse = {
  /**
   * Portal Url
   *
   * Stripe customer portal URL
   */
  portal_url: string;
};

/**
 * QuantityUpdate
 *
 * Schema for updating item quantity.
 */
export type QuantityUpdate = {
  /**
   * Quantity
   */
  quantity: number;
};

/**
 * RefundRequest
 *
 * Request schema for refunding a purchase.
 */
export type RefundRequest = {
  /**
   * Transaction Id
   *
   * Transaction ID to refund
   */
  transaction_id: string;
};

/**
 * RefundResponse
 *
 * Response schema for refund.
 */
export type RefundResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Refunded Credits
   */
  refunded_credits?: number;
};

/**
 * TimeSeriesDataPoint
 *
 * A single data point in a time series.
 */
export type TimeSeriesDataPoint = {
  /**
   * Date
   */
  date: string;
  /**
   * Count
   */
  count: number;
};

/**
 * TokenResponse
 *
 * Schema for authentication token response.
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
  /**
   * Expires In
   */
  expires_in: number;
};

/**
 * TransactionResponse
 *
 * Response schema for credit transaction.
 */
export type TransactionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Transaction Type
   */
  transaction_type: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Refunded
   */
  is_refunded?: boolean;
  /**
   * Created At
   */
  created_at: string;
  credit_pack?: CreditPackResponse | null;
};

/**
 * UserAdminResponse
 *
 * Admin response schema for user.
 */
export type UserAdminResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string | null;
  /**
   * Avatar Url
   */
  avatar_url: string | null;
  /**
   * Is Admin
   */
  is_admin: boolean;
  /**
   * Credit Balance
   */
  credit_balance: number;
  /**
   * Free Credits Remaining
   */
  free_credits_remaining: number;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * UserAdminUpdate
 *
 * Schema for admin updating a user.
 */
export type UserAdminUpdate = {
  /**
   * Is Admin
   */
  is_admin: boolean;
};

/**
 * UserResponse
 *
 * Schema for user responses.
 */
export type UserResponse = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Avatar Url
   */
  avatar_url?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Is Admin
   */
  is_admin?: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListPacksApiV1AdminPacksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/admin/packs";
};

export type ListPacksApiV1AdminPacksGetResponses = {
  /**
   * Response List Packs Api V1 Admin Packs Get
   *
   * Successful Response
   */
  200: Array<CreditPackAdminResponse>;
};

export type ListPacksApiV1AdminPacksGetResponse =
  ListPacksApiV1AdminPacksGetResponses[keyof ListPacksApiV1AdminPacksGetResponses];

export type CreatePackApiV1AdminPacksPostData = {
  body: CreditPackCreate;
  path?: never;
  query?: never;
  url: "/api/v1/admin/packs";
};

export type CreatePackApiV1AdminPacksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePackApiV1AdminPacksPostError =
  CreatePackApiV1AdminPacksPostErrors[keyof CreatePackApiV1AdminPacksPostErrors];

export type CreatePackApiV1AdminPacksPostResponses = {
  /**
   * Successful Response
   */
  201: CreditPackAdminResponse;
};

export type CreatePackApiV1AdminPacksPostResponse =
  CreatePackApiV1AdminPacksPostResponses[keyof CreatePackApiV1AdminPacksPostResponses];

export type DeletePackApiV1AdminPacksPackIdDeleteData = {
  body?: never;
  path: {
    /**
     * Pack Id
     */
    pack_id: string;
  };
  query?: never;
  url: "/api/v1/admin/packs/{pack_id}";
};

export type DeletePackApiV1AdminPacksPackIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePackApiV1AdminPacksPackIdDeleteError =
  DeletePackApiV1AdminPacksPackIdDeleteErrors[keyof DeletePackApiV1AdminPacksPackIdDeleteErrors];

export type DeletePackApiV1AdminPacksPackIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeletePackApiV1AdminPacksPackIdDeleteResponse =
  DeletePackApiV1AdminPacksPackIdDeleteResponses[keyof DeletePackApiV1AdminPacksPackIdDeleteResponses];

export type GetPackApiV1AdminPacksPackIdGetData = {
  body?: never;
  path: {
    /**
     * Pack Id
     */
    pack_id: string;
  };
  query?: never;
  url: "/api/v1/admin/packs/{pack_id}";
};

export type GetPackApiV1AdminPacksPackIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPackApiV1AdminPacksPackIdGetError =
  GetPackApiV1AdminPacksPackIdGetErrors[keyof GetPackApiV1AdminPacksPackIdGetErrors];

export type GetPackApiV1AdminPacksPackIdGetResponses = {
  /**
   * Successful Response
   */
  200: CreditPackAdminResponse;
};

export type GetPackApiV1AdminPacksPackIdGetResponse =
  GetPackApiV1AdminPacksPackIdGetResponses[keyof GetPackApiV1AdminPacksPackIdGetResponses];

export type UpdatePackApiV1AdminPacksPackIdPutData = {
  body: CreditPackUpdate;
  path: {
    /**
     * Pack Id
     */
    pack_id: string;
  };
  query?: never;
  url: "/api/v1/admin/packs/{pack_id}";
};

export type UpdatePackApiV1AdminPacksPackIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePackApiV1AdminPacksPackIdPutError =
  UpdatePackApiV1AdminPacksPackIdPutErrors[keyof UpdatePackApiV1AdminPacksPackIdPutErrors];

export type UpdatePackApiV1AdminPacksPackIdPutResponses = {
  /**
   * Successful Response
   */
  200: CreditPackAdminResponse;
};

export type UpdatePackApiV1AdminPacksPackIdPutResponse =
  UpdatePackApiV1AdminPacksPackIdPutResponses[keyof UpdatePackApiV1AdminPacksPackIdPutResponses];

export type ListUsersApiV1AdminUsersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Search
     *
     * Search by email
     */
    search?: string | null;
  };
  url: "/api/v1/admin/users";
};

export type ListUsersApiV1AdminUsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUsersApiV1AdminUsersGetError =
  ListUsersApiV1AdminUsersGetErrors[keyof ListUsersApiV1AdminUsersGetErrors];

export type ListUsersApiV1AdminUsersGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedUsersResponse;
};

export type ListUsersApiV1AdminUsersGetResponse =
  ListUsersApiV1AdminUsersGetResponses[keyof ListUsersApiV1AdminUsersGetResponses];

export type GetUserApiV1AdminUsersUserIdGetData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/admin/users/{user_id}";
};

export type GetUserApiV1AdminUsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserApiV1AdminUsersUserIdGetError =
  GetUserApiV1AdminUsersUserIdGetErrors[keyof GetUserApiV1AdminUsersUserIdGetErrors];

export type GetUserApiV1AdminUsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserAdminResponse;
};

export type GetUserApiV1AdminUsersUserIdGetResponse =
  GetUserApiV1AdminUsersUserIdGetResponses[keyof GetUserApiV1AdminUsersUserIdGetResponses];

export type UpdateUserApiV1AdminUsersUserIdPutData = {
  body: UserAdminUpdate;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/admin/users/{user_id}";
};

export type UpdateUserApiV1AdminUsersUserIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserApiV1AdminUsersUserIdPutError =
  UpdateUserApiV1AdminUsersUserIdPutErrors[keyof UpdateUserApiV1AdminUsersUserIdPutErrors];

export type UpdateUserApiV1AdminUsersUserIdPutResponses = {
  /**
   * Successful Response
   */
  200: UserAdminResponse;
};

export type UpdateUserApiV1AdminUsersUserIdPutResponse =
  UpdateUserApiV1AdminUsersUserIdPutResponses[keyof UpdateUserApiV1AdminUsersUserIdPutResponses];

export type AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostData = {
  body: CreditAdjustmentRequest;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/admin/users/{user_id}/credits";
};

export type AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostError =
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors[keyof AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostErrors];

export type AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses = {
  /**
   * Successful Response
   */
  200: CreditAdjustmentResponse;
};

export type AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponse =
  AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses[keyof AdjustUserCreditsApiV1AdminUsersUserIdCreditsPostResponses];

export type GetStatsApiV1AdminStatsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/admin/stats";
};

export type GetStatsApiV1AdminStatsGetResponses = {
  /**
   * Successful Response
   */
  200: AdminStatsResponse;
};

export type GetStatsApiV1AdminStatsGetResponse =
  GetStatsApiV1AdminStatsGetResponses[keyof GetStatsApiV1AdminStatsGetResponses];

export type GoogleAuthApiV1AuthGoogleGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Redirect Uri
     *
     * The redirect URI for OAuth callback
     */
    redirect_uri: string;
  };
  url: "/api/v1/auth/google";
};

export type GoogleAuthApiV1AuthGoogleGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GoogleAuthApiV1AuthGoogleGetError =
  GoogleAuthApiV1AuthGoogleGetErrors[keyof GoogleAuthApiV1AuthGoogleGetErrors];

export type GoogleAuthApiV1AuthGoogleGetResponses = {
  /**
   * Response Google Auth Api V1 Auth Google Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type GoogleAuthApiV1AuthGoogleGetResponse =
  GoogleAuthApiV1AuthGoogleGetResponses[keyof GoogleAuthApiV1AuthGoogleGetResponses];

export type GoogleCallbackApiV1AuthCallbackGoogleGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     */
    code: string;
    /**
     * Redirect Uri
     */
    redirect_uri: string;
  };
  url: "/api/v1/auth/callback/google";
};

export type GoogleCallbackApiV1AuthCallbackGoogleGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GoogleCallbackApiV1AuthCallbackGoogleGetError =
  GoogleCallbackApiV1AuthCallbackGoogleGetErrors[keyof GoogleCallbackApiV1AuthCallbackGoogleGetErrors];

export type GoogleCallbackApiV1AuthCallbackGoogleGetResponses = {
  /**
   * Successful Response
   */
  200: AuthResponse;
};

export type GoogleCallbackApiV1AuthCallbackGoogleGetResponse =
  GoogleCallbackApiV1AuthCallbackGoogleGetResponses[keyof GoogleCallbackApiV1AuthCallbackGoogleGetResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse =
  GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type RefreshTokenApiV1AuthRefreshPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/refresh";
};

export type RefreshTokenApiV1AuthRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RefreshTokenApiV1AuthRefreshPostResponse =
  RefreshTokenApiV1AuthRefreshPostResponses[keyof RefreshTokenApiV1AuthRefreshPostResponses];

export type GetBalanceApiV1BillingBalanceGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/balance";
};

export type GetBalanceApiV1BillingBalanceGetResponses = {
  /**
   * Successful Response
   */
  200: CreditBalanceResponse;
};

export type GetBalanceApiV1BillingBalanceGetResponse =
  GetBalanceApiV1BillingBalanceGetResponses[keyof GetBalanceApiV1BillingBalanceGetResponses];

export type ListPacksApiV1BillingPacksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/packs";
};

export type ListPacksApiV1BillingPacksGetResponses = {
  /**
   * Response List Packs Api V1 Billing Packs Get
   *
   * Successful Response
   */
  200: Array<CreditPackResponse>;
};

export type ListPacksApiV1BillingPacksGetResponse =
  ListPacksApiV1BillingPacksGetResponses[keyof ListPacksApiV1BillingPacksGetResponses];

export type CreateCheckoutApiV1BillingCheckoutPostData = {
  body: CheckoutRequest;
  path?: never;
  query?: never;
  url: "/api/v1/billing/checkout";
};

export type CreateCheckoutApiV1BillingCheckoutPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCheckoutApiV1BillingCheckoutPostError =
  CreateCheckoutApiV1BillingCheckoutPostErrors[keyof CreateCheckoutApiV1BillingCheckoutPostErrors];

export type CreateCheckoutApiV1BillingCheckoutPostResponses = {
  /**
   * Successful Response
   */
  200: CheckoutResponse;
};

export type CreateCheckoutApiV1BillingCheckoutPostResponse =
  CreateCheckoutApiV1BillingCheckoutPostResponses[keyof CreateCheckoutApiV1BillingCheckoutPostResponses];

export type ListTransactionsApiV1BillingTransactionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/billing/transactions";
};

export type ListTransactionsApiV1BillingTransactionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTransactionsApiV1BillingTransactionsGetError =
  ListTransactionsApiV1BillingTransactionsGetErrors[keyof ListTransactionsApiV1BillingTransactionsGetErrors];

export type ListTransactionsApiV1BillingTransactionsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedTransactionResponse;
};

export type ListTransactionsApiV1BillingTransactionsGetResponse =
  ListTransactionsApiV1BillingTransactionsGetResponses[keyof ListTransactionsApiV1BillingTransactionsGetResponses];

export type CreatePortalSessionApiV1BillingPortalPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/portal";
};

export type CreatePortalSessionApiV1BillingPortalPostResponses = {
  /**
   * Successful Response
   */
  200: PortalResponse;
};

export type CreatePortalSessionApiV1BillingPortalPostResponse =
  CreatePortalSessionApiV1BillingPortalPostResponses[keyof CreatePortalSessionApiV1BillingPortalPostResponses];

export type RequestRefundApiV1BillingRefundPostData = {
  body: RefundRequest;
  path?: never;
  query?: never;
  url: "/api/v1/billing/refund";
};

export type RequestRefundApiV1BillingRefundPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RequestRefundApiV1BillingRefundPostError =
  RequestRefundApiV1BillingRefundPostErrors[keyof RequestRefundApiV1BillingRefundPostErrors];

export type RequestRefundApiV1BillingRefundPostResponses = {
  /**
   * Successful Response
   */
  200: RefundResponse;
};

export type RequestRefundApiV1BillingRefundPostResponse =
  RequestRefundApiV1BillingRefundPostResponses[keyof RequestRefundApiV1BillingRefundPostResponses];

export type HandleWebhookApiV1BillingWebhookPostData = {
  body?: never;
  headers: {
    /**
     * Stripe-Signature
     */
    "Stripe-Signature": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/billing/webhook";
};

export type HandleWebhookApiV1BillingWebhookPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type HandleWebhookApiV1BillingWebhookPostError =
  HandleWebhookApiV1BillingWebhookPostErrors[keyof HandleWebhookApiV1BillingWebhookPostErrors];

export type HandleWebhookApiV1BillingWebhookPostResponses = {
  /**
   * Response Handle Webhook Api V1 Billing Webhook Post
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type HandleWebhookApiV1BillingWebhookPostResponse =
  HandleWebhookApiV1BillingWebhookPostResponses[keyof HandleWebhookApiV1BillingWebhookPostResponses];

export type ListItemsApiV1ItemsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Include Subcategories
     *
     * Include items from subcategories
     */
    include_subcategories?: boolean;
    /**
     * Location Id
     */
    location_id?: string | null;
    /**
     * Include Sublocations
     *
     * Include items from sublocations
     */
    include_sublocations?: boolean;
    /**
     * Search
     */
    search?: string | null;
    /**
     * Tags
     *
     * Filter by tags (AND logic)
     */
    tags?: Array<string> | null;
    /**
     * Attr
     *
     * Filter by attributes as key:value pairs
     */
    attr?: Array<string> | null;
    /**
     * Low Stock
     */
    low_stock?: boolean;
    /**
     * Page
     */
    page?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items";
};

export type ListItemsApiV1ItemsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListItemsApiV1ItemsGetError =
  ListItemsApiV1ItemsGetErrors[keyof ListItemsApiV1ItemsGetErrors];

export type ListItemsApiV1ItemsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseItemListResponse;
};

export type ListItemsApiV1ItemsGetResponse =
  ListItemsApiV1ItemsGetResponses[keyof ListItemsApiV1ItemsGetResponses];

export type CreateItemApiV1ItemsPostData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items";
};

export type CreateItemApiV1ItemsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError =
  CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
  /**
   * Successful Response
   */
  201: ItemDetailResponse;
};

export type CreateItemApiV1ItemsPostResponse =
  CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type GetDashboardStatsApiV1ItemsStatsDashboardGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Days
     */
    days?: number;
  };
  url: "/api/v1/items/stats/dashboard";
};

export type GetDashboardStatsApiV1ItemsStatsDashboardGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDashboardStatsApiV1ItemsStatsDashboardGetError =
  GetDashboardStatsApiV1ItemsStatsDashboardGetErrors[keyof GetDashboardStatsApiV1ItemsStatsDashboardGetErrors];

export type GetDashboardStatsApiV1ItemsStatsDashboardGetResponses = {
  /**
   * Successful Response
   */
  200: DashboardStatsResponse;
};

export type GetDashboardStatsApiV1ItemsStatsDashboardGetResponse =
  GetDashboardStatsApiV1ItemsStatsDashboardGetResponses[keyof GetDashboardStatsApiV1ItemsStatsDashboardGetResponses];

export type SearchItemsApiV1ItemsSearchGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Q
     */
    q: string;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items/search";
};

export type SearchItemsApiV1ItemsSearchGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchItemsApiV1ItemsSearchGetError =
  SearchItemsApiV1ItemsSearchGetErrors[keyof SearchItemsApiV1ItemsSearchGetErrors];

export type SearchItemsApiV1ItemsSearchGetResponses = {
  /**
   * Response Search Items Api V1 Items Search Get
   *
   * Successful Response
   */
  200: Array<ItemListResponse>;
};

export type SearchItemsApiV1ItemsSearchGetResponse =
  SearchItemsApiV1ItemsSearchGetResponses[keyof SearchItemsApiV1ItemsSearchGetResponses];

export type ListLowStockItemsApiV1ItemsLowStockGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/items/low-stock";
};

export type ListLowStockItemsApiV1ItemsLowStockGetResponses = {
  /**
   * Response List Low Stock Items Api V1 Items Low Stock Get
   *
   * Successful Response
   */
  200: Array<ItemListResponse>;
};

export type ListLowStockItemsApiV1ItemsLowStockGetResponse =
  ListLowStockItemsApiV1ItemsLowStockGetResponses[keyof ListLowStockItemsApiV1ItemsLowStockGetResponses];

export type GetItemFacetsApiV1ItemsFacetsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Category Id
     *
     * Filter facets by category
     */
    category_id?: string | null;
    /**
     * Include Subcategories
     *
     * Include items from subcategories
     */
    include_subcategories?: boolean;
    /**
     * Location Id
     *
     * Filter facets by location
     */
    location_id?: string | null;
    /**
     * Include Sublocations
     *
     * Include items from sublocations
     */
    include_sublocations?: boolean;
  };
  url: "/api/v1/items/facets";
};

export type GetItemFacetsApiV1ItemsFacetsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetItemFacetsApiV1ItemsFacetsGetError =
  GetItemFacetsApiV1ItemsFacetsGetErrors[keyof GetItemFacetsApiV1ItemsFacetsGetErrors];

export type GetItemFacetsApiV1ItemsFacetsGetResponses = {
  /**
   * Successful Response
   */
  200: FacetedSearchResponse;
};

export type GetItemFacetsApiV1ItemsFacetsGetResponse =
  GetItemFacetsApiV1ItemsFacetsGetResponses[keyof GetItemFacetsApiV1ItemsFacetsGetResponses];

export type GetAllTagsApiV1ItemsTagsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items/tags";
};

export type GetAllTagsApiV1ItemsTagsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAllTagsApiV1ItemsTagsGetError =
  GetAllTagsApiV1ItemsTagsGetErrors[keyof GetAllTagsApiV1ItemsTagsGetErrors];

export type GetAllTagsApiV1ItemsTagsGetResponses = {
  /**
   * Response Get All Tags Api V1 Items Tags Get
   *
   * Successful Response
   */
  200: Array<FacetValue>;
};

export type GetAllTagsApiV1ItemsTagsGetResponse =
  GetAllTagsApiV1ItemsTagsGetResponses[keyof GetAllTagsApiV1ItemsTagsGetResponses];

export type DeleteItemApiV1ItemsItemIdDeleteData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type DeleteItemApiV1ItemsItemIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemApiV1ItemsItemIdDeleteError =
  DeleteItemApiV1ItemsItemIdDeleteErrors[keyof DeleteItemApiV1ItemsItemIdDeleteErrors];

export type DeleteItemApiV1ItemsItemIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse =
  DeleteItemApiV1ItemsItemIdDeleteResponses[keyof DeleteItemApiV1ItemsItemIdDeleteResponses];

export type GetItemApiV1ItemsItemIdGetData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type GetItemApiV1ItemsItemIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetItemApiV1ItemsItemIdGetError =
  GetItemApiV1ItemsItemIdGetErrors[keyof GetItemApiV1ItemsItemIdGetErrors];

export type GetItemApiV1ItemsItemIdGetResponses = {
  /**
   * Successful Response
   */
  200: ItemDetailResponse;
};

export type GetItemApiV1ItemsItemIdGetResponse =
  GetItemApiV1ItemsItemIdGetResponses[keyof GetItemApiV1ItemsItemIdGetResponses];

export type UpdateItemApiV1ItemsItemIdPutData = {
  body: ItemUpdate;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type UpdateItemApiV1ItemsItemIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateItemApiV1ItemsItemIdPutError =
  UpdateItemApiV1ItemsItemIdPutErrors[keyof UpdateItemApiV1ItemsItemIdPutErrors];

export type UpdateItemApiV1ItemsItemIdPutResponses = {
  /**
   * Successful Response
   */
  200: ItemDetailResponse;
};

export type UpdateItemApiV1ItemsItemIdPutResponse =
  UpdateItemApiV1ItemsItemIdPutResponses[keyof UpdateItemApiV1ItemsItemIdPutResponses];

export type UpdateItemQuantityApiV1ItemsItemIdQuantityPatchData = {
  body: QuantityUpdate;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/v1/items/{item_id}/quantity";
};

export type UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateItemQuantityApiV1ItemsItemIdQuantityPatchError =
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors[keyof UpdateItemQuantityApiV1ItemsItemIdQuantityPatchErrors];

export type UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses = {
  /**
   * Successful Response
   */
  200: ItemDetailResponse;
};

export type UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponse =
  UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses[keyof UpdateItemQuantityApiV1ItemsItemIdQuantityPatchResponses];

export type ListCategoriesApiV1CategoriesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/categories";
};

export type ListCategoriesApiV1CategoriesGetResponses = {
  /**
   * Response List Categories Api V1 Categories Get
   *
   * Successful Response
   */
  200: Array<CategoryResponse>;
};

export type ListCategoriesApiV1CategoriesGetResponse =
  ListCategoriesApiV1CategoriesGetResponses[keyof ListCategoriesApiV1CategoriesGetResponses];

export type CreateCategoryApiV1CategoriesPostData = {
  body: CategoryCreate;
  path?: never;
  query?: never;
  url: "/api/v1/categories";
};

export type CreateCategoryApiV1CategoriesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCategoryApiV1CategoriesPostError =
  CreateCategoryApiV1CategoriesPostErrors[keyof CreateCategoryApiV1CategoriesPostErrors];

export type CreateCategoryApiV1CategoriesPostResponses = {
  /**
   * Successful Response
   */
  201: CategoryResponse;
};

export type CreateCategoryApiV1CategoriesPostResponse =
  CreateCategoryApiV1CategoriesPostResponses[keyof CreateCategoryApiV1CategoriesPostResponses];

export type GetCategoryTreeApiV1CategoriesTreeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/categories/tree";
};

export type GetCategoryTreeApiV1CategoriesTreeGetResponses = {
  /**
   * Response Get Category Tree Api V1 Categories Tree Get
   *
   * Successful Response
   */
  200: Array<CategoryTreeNode>;
};

export type GetCategoryTreeApiV1CategoriesTreeGetResponse =
  GetCategoryTreeApiV1CategoriesTreeGetResponses[keyof GetCategoryTreeApiV1CategoriesTreeGetResponses];

export type CreateCategoryFromPathApiV1CategoriesFromPathPostData = {
  body: CategoryCreateFromPath;
  path?: never;
  query?: never;
  url: "/api/v1/categories/from-path";
};

export type CreateCategoryFromPathApiV1CategoriesFromPathPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCategoryFromPathApiV1CategoriesFromPathPostError =
  CreateCategoryFromPathApiV1CategoriesFromPathPostErrors[keyof CreateCategoryFromPathApiV1CategoriesFromPathPostErrors];

export type CreateCategoryFromPathApiV1CategoriesFromPathPostResponses = {
  /**
   * Successful Response
   */
  201: CategoryResponse;
};

export type CreateCategoryFromPathApiV1CategoriesFromPathPostResponse =
  CreateCategoryFromPathApiV1CategoriesFromPathPostResponses[keyof CreateCategoryFromPathApiV1CategoriesFromPathPostResponses];

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteData = {
  body?: never;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/api/v1/categories/{category_id}";
};

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteError =
  DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors[keyof DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors];

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteResponse =
  DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses[keyof DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses];

export type GetCategoryApiV1CategoriesCategoryIdGetData = {
  body?: never;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/api/v1/categories/{category_id}";
};

export type GetCategoryApiV1CategoriesCategoryIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCategoryApiV1CategoriesCategoryIdGetError =
  GetCategoryApiV1CategoriesCategoryIdGetErrors[keyof GetCategoryApiV1CategoriesCategoryIdGetErrors];

export type GetCategoryApiV1CategoriesCategoryIdGetResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type GetCategoryApiV1CategoriesCategoryIdGetResponse =
  GetCategoryApiV1CategoriesCategoryIdGetResponses[keyof GetCategoryApiV1CategoriesCategoryIdGetResponses];

export type UpdateCategoryApiV1CategoriesCategoryIdPutData = {
  body: CategoryUpdate;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/api/v1/categories/{category_id}";
};

export type UpdateCategoryApiV1CategoriesCategoryIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCategoryApiV1CategoriesCategoryIdPutError =
  UpdateCategoryApiV1CategoriesCategoryIdPutErrors[keyof UpdateCategoryApiV1CategoriesCategoryIdPutErrors];

export type UpdateCategoryApiV1CategoriesCategoryIdPutResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type UpdateCategoryApiV1CategoriesCategoryIdPutResponse =
  UpdateCategoryApiV1CategoriesCategoryIdPutResponses[keyof UpdateCategoryApiV1CategoriesCategoryIdPutResponses];

export type GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetData = {
  body?: never;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/api/v1/categories/{category_id}/template";
};

export type GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetError =
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors[keyof GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetErrors];

export type GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses = {
  /**
   * Successful Response
   */
  200: MergedAttributeTemplate;
};

export type GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponse =
  GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses[keyof GetCategoryTemplateApiV1CategoriesCategoryIdTemplateGetResponses];

export type GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetData =
  {
    body?: never;
    path: {
      /**
       * Category Id
       */
      category_id: string;
    };
    query?: never;
    url: "/api/v1/categories/{category_id}/descendants";
  };

export type GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetError =
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors[keyof GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetErrors];

export type GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses =
  {
    /**
     * Response Get Category Descendants Api V1 Categories  Category Id  Descendants Get
     *
     * Successful Response
     */
    200: Array<CategoryResponse>;
  };

export type GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponse =
  GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses[keyof GetCategoryDescendantsApiV1CategoriesCategoryIdDescendantsGetResponses];

export type MoveCategoryApiV1CategoriesCategoryIdMovePatchData = {
  body: CategoryMoveRequest;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/api/v1/categories/{category_id}/move";
};

export type MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MoveCategoryApiV1CategoriesCategoryIdMovePatchError =
  MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors[keyof MoveCategoryApiV1CategoriesCategoryIdMovePatchErrors];

export type MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type MoveCategoryApiV1CategoriesCategoryIdMovePatchResponse =
  MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses[keyof MoveCategoryApiV1CategoriesCategoryIdMovePatchResponses];

export type ListLocationsApiV1LocationsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/locations";
};

export type ListLocationsApiV1LocationsGetResponses = {
  /**
   * Response List Locations Api V1 Locations Get
   *
   * Successful Response
   */
  200: Array<LocationResponse>;
};

export type ListLocationsApiV1LocationsGetResponse =
  ListLocationsApiV1LocationsGetResponses[keyof ListLocationsApiV1LocationsGetResponses];

export type CreateLocationApiV1LocationsPostData = {
  body: LocationCreate;
  path?: never;
  query?: never;
  url: "/api/v1/locations";
};

export type CreateLocationApiV1LocationsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateLocationApiV1LocationsPostError =
  CreateLocationApiV1LocationsPostErrors[keyof CreateLocationApiV1LocationsPostErrors];

export type CreateLocationApiV1LocationsPostResponses = {
  /**
   * Successful Response
   */
  201: LocationResponse;
};

export type CreateLocationApiV1LocationsPostResponse =
  CreateLocationApiV1LocationsPostResponses[keyof CreateLocationApiV1LocationsPostResponses];

export type GetLocationTreeApiV1LocationsTreeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/locations/tree";
};

export type GetLocationTreeApiV1LocationsTreeGetResponses = {
  /**
   * Response Get Location Tree Api V1 Locations Tree Get
   *
   * Successful Response
   */
  200: Array<LocationTreeNode>;
};

export type GetLocationTreeApiV1LocationsTreeGetResponse =
  GetLocationTreeApiV1LocationsTreeGetResponses[keyof GetLocationTreeApiV1LocationsTreeGetResponses];

export type DeleteLocationApiV1LocationsLocationIdDeleteData = {
  body?: never;
  path: {
    /**
     * Location Id
     */
    location_id: string;
  };
  query?: never;
  url: "/api/v1/locations/{location_id}";
};

export type DeleteLocationApiV1LocationsLocationIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteLocationApiV1LocationsLocationIdDeleteError =
  DeleteLocationApiV1LocationsLocationIdDeleteErrors[keyof DeleteLocationApiV1LocationsLocationIdDeleteErrors];

export type DeleteLocationApiV1LocationsLocationIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteLocationApiV1LocationsLocationIdDeleteResponse =
  DeleteLocationApiV1LocationsLocationIdDeleteResponses[keyof DeleteLocationApiV1LocationsLocationIdDeleteResponses];

export type GetLocationApiV1LocationsLocationIdGetData = {
  body?: never;
  path: {
    /**
     * Location Id
     */
    location_id: string;
  };
  query?: never;
  url: "/api/v1/locations/{location_id}";
};

export type GetLocationApiV1LocationsLocationIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLocationApiV1LocationsLocationIdGetError =
  GetLocationApiV1LocationsLocationIdGetErrors[keyof GetLocationApiV1LocationsLocationIdGetErrors];

export type GetLocationApiV1LocationsLocationIdGetResponses = {
  /**
   * Successful Response
   */
  200: LocationResponse;
};

export type GetLocationApiV1LocationsLocationIdGetResponse =
  GetLocationApiV1LocationsLocationIdGetResponses[keyof GetLocationApiV1LocationsLocationIdGetResponses];

export type UpdateLocationApiV1LocationsLocationIdPutData = {
  body: LocationUpdate;
  path: {
    /**
     * Location Id
     */
    location_id: string;
  };
  query?: never;
  url: "/api/v1/locations/{location_id}";
};

export type UpdateLocationApiV1LocationsLocationIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateLocationApiV1LocationsLocationIdPutError =
  UpdateLocationApiV1LocationsLocationIdPutErrors[keyof UpdateLocationApiV1LocationsLocationIdPutErrors];

export type UpdateLocationApiV1LocationsLocationIdPutResponses = {
  /**
   * Successful Response
   */
  200: LocationResponse;
};

export type UpdateLocationApiV1LocationsLocationIdPutResponse =
  UpdateLocationApiV1LocationsLocationIdPutResponses[keyof UpdateLocationApiV1LocationsLocationIdPutResponses];

export type GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetData = {
  body?: never;
  path: {
    /**
     * Location Id
     */
    location_id: string;
  };
  query?: never;
  url: "/api/v1/locations/{location_id}/descendants";
};

export type GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetError =
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors[keyof GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetErrors];

export type GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses =
  {
    /**
     * Response Get Location Descendants Api V1 Locations  Location Id  Descendants Get
     *
     * Successful Response
     */
    200: Array<LocationResponse>;
  };

export type GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponse =
  GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses[keyof GetLocationDescendantsApiV1LocationsLocationIdDescendantsGetResponses];

export type MoveLocationApiV1LocationsLocationIdMovePatchData = {
  body: LocationMoveRequest;
  path: {
    /**
     * Location Id
     */
    location_id: string;
  };
  query?: never;
  url: "/api/v1/locations/{location_id}/move";
};

export type MoveLocationApiV1LocationsLocationIdMovePatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MoveLocationApiV1LocationsLocationIdMovePatchError =
  MoveLocationApiV1LocationsLocationIdMovePatchErrors[keyof MoveLocationApiV1LocationsLocationIdMovePatchErrors];

export type MoveLocationApiV1LocationsLocationIdMovePatchResponses = {
  /**
   * Successful Response
   */
  200: LocationResponse;
};

export type MoveLocationApiV1LocationsLocationIdMovePatchResponse =
  MoveLocationApiV1LocationsLocationIdMovePatchResponses[keyof MoveLocationApiV1LocationsLocationIdMovePatchResponses];

export type UploadImageApiV1ImagesUploadPostData = {
  body: BodyUploadImageApiV1ImagesUploadPost;
  path?: never;
  query?: never;
  url: "/api/v1/images/upload";
};

export type UploadImageApiV1ImagesUploadPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadImageApiV1ImagesUploadPostError =
  UploadImageApiV1ImagesUploadPostErrors[keyof UploadImageApiV1ImagesUploadPostErrors];

export type UploadImageApiV1ImagesUploadPostResponses = {
  /**
   * Successful Response
   */
  201: ImageUploadResponse;
};

export type UploadImageApiV1ImagesUploadPostResponse =
  UploadImageApiV1ImagesUploadPostResponses[keyof UploadImageApiV1ImagesUploadPostResponses];

export type ClassifyImageApiV1ImagesClassifyPostData = {
  body: ClassificationRequest;
  path?: never;
  query?: never;
  url: "/api/v1/images/classify";
};

export type ClassifyImageApiV1ImagesClassifyPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClassifyImageApiV1ImagesClassifyPostError =
  ClassifyImageApiV1ImagesClassifyPostErrors[keyof ClassifyImageApiV1ImagesClassifyPostErrors];

export type ClassifyImageApiV1ImagesClassifyPostResponses = {
  /**
   * Successful Response
   */
  200: ClassificationResponse;
};

export type ClassifyImageApiV1ImagesClassifyPostResponse =
  ClassifyImageApiV1ImagesClassifyPostResponses[keyof ClassifyImageApiV1ImagesClassifyPostResponses];

export type ListClassifiedImagesApiV1ImagesClassifiedGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/images/classified";
};

export type ListClassifiedImagesApiV1ImagesClassifiedGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListClassifiedImagesApiV1ImagesClassifiedGetError =
  ListClassifiedImagesApiV1ImagesClassifiedGetErrors[keyof ListClassifiedImagesApiV1ImagesClassifiedGetErrors];

export type ListClassifiedImagesApiV1ImagesClassifiedGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedImagesResponse;
};

export type ListClassifiedImagesApiV1ImagesClassifiedGetResponse =
  ListClassifiedImagesApiV1ImagesClassifiedGetResponses[keyof ListClassifiedImagesApiV1ImagesClassifiedGetResponses];

export type DeleteImageApiV1ImagesImageIdDeleteData = {
  body?: never;
  path: {
    /**
     * Image Id
     */
    image_id: string;
  };
  query?: never;
  url: "/api/v1/images/{image_id}";
};

export type DeleteImageApiV1ImagesImageIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteImageApiV1ImagesImageIdDeleteError =
  DeleteImageApiV1ImagesImageIdDeleteErrors[keyof DeleteImageApiV1ImagesImageIdDeleteErrors];

export type DeleteImageApiV1ImagesImageIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteImageApiV1ImagesImageIdDeleteResponse =
  DeleteImageApiV1ImagesImageIdDeleteResponses[keyof DeleteImageApiV1ImagesImageIdDeleteResponses];

export type GetImageApiV1ImagesImageIdGetData = {
  body?: never;
  path: {
    /**
     * Image Id
     */
    image_id: string;
  };
  query?: never;
  url: "/api/v1/images/{image_id}";
};

export type GetImageApiV1ImagesImageIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetImageApiV1ImagesImageIdGetError =
  GetImageApiV1ImagesImageIdGetErrors[keyof GetImageApiV1ImagesImageIdGetErrors];

export type GetImageApiV1ImagesImageIdGetResponses = {
  /**
   * Successful Response
   */
  200: ImageResponse;
};

export type GetImageApiV1ImagesImageIdGetResponse =
  GetImageApiV1ImagesImageIdGetResponses[keyof GetImageApiV1ImagesImageIdGetResponses];

export type GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetData = {
  body?: never;
  path: {
    /**
     * Image Id
     */
    image_id: string;
  };
  query?: never;
  url: "/api/v1/images/{image_id}/signed-url";
};

export type GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetError =
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors[keyof GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetErrors];

export type GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses = {
  /**
   * Successful Response
   */
  200: ImageSignedUrlResponse;
};

export type GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponse =
  GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses[keyof GetImageSignedUrlApiV1ImagesImageIdSignedUrlGetResponses];

export type GetImageFileApiV1ImagesImageIdFileGetData = {
  body?: never;
  path: {
    /**
     * Image Id
     */
    image_id: string;
  };
  query?: {
    /**
     * Token
     */
    token?: string | null;
  };
  url: "/api/v1/images/{image_id}/file";
};

export type GetImageFileApiV1ImagesImageIdFileGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetImageFileApiV1ImagesImageIdFileGetError =
  GetImageFileApiV1ImagesImageIdFileGetErrors[keyof GetImageFileApiV1ImagesImageIdFileGetErrors];

export type GetImageFileApiV1ImagesImageIdFileGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AttachImageToItemApiV1ImagesImageIdAttachItemIdPostData = {
  body?: never;
  path: {
    /**
     * Image Id
     */
    image_id: string;
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: {
    /**
     * Is Primary
     */
    is_primary?: boolean;
  };
  url: "/api/v1/images/{image_id}/attach/{item_id}";
};

export type AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AttachImageToItemApiV1ImagesImageIdAttachItemIdPostError =
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors[keyof AttachImageToItemApiV1ImagesImageIdAttachItemIdPostErrors];

export type AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses = {
  /**
   * Successful Response
   */
  200: ImageResponse;
};

export type AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponse =
  AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses[keyof AttachImageToItemApiV1ImagesImageIdAttachItemIdPostResponses];
